export const Gender = ["M", "F"];
export const title_level = [
  {label: "C Suite", value:"C Level"},
  { label: "Practitioner", value: "Practitioner" },
  { label: "Director Level", value: "Director Level" },
  { label: "Manager Level", value: "Manager Level" },
  { label: "Staff Level", value: "Staff Level" },
  { label: "Senior Level", value: "Senior Level" },
  // "C Suite",
  // "Practitioner",
  // "Director Level",
  // "Manager Level",
  // "Staff Level",
  // "Senior Level",
  // "Other",
];
export const OwnerShip = ["Private", "Non-Profit/Public"];

export const PracticeLocationRange = [
  "Small/Emerging 3-9 locations",
  "Mid-Market 10-75 locations",
  "Elite 76  locations",
  "Mobile locations",
];

export const Department = [
  "CEO/President/Owner/MD",
  "Operations",
  "Information Technology",
  "Marketing",
  "Sales",
  "Finance/Accounting",
  "Research",
  "Purchasing/Procurement",
  "Customer Services",
  "Medical",
  "Other C-Suite",
  "Training",
  "Business Development",
  "Engineering",
  "Others",
  "Human Resources",
];

export const Speciality = [
  'General Dentist',
  'Oral & Maxillofacial Surgeon',
  'Pedodontist (Pediatric Dentist)',
  'Orthodontist',
  'Endodontist',
  'Prosthodontist',
  'Periodontist',
  'Dentist',
  'Oral & Maxillofacial Pathologist',
  'Dentist Anesthesiologist',
  'Oral & Maxillofacial Radiologist',
  'Pediatric Dentist',
  'Oral and Maxillofacial Surgeon',
  'Orthodontist & Dentofacial Orthopedics',
  'General & Cosmetic Dentist',
  'Orthodontist & Pediatric Dentist',
  'Oral and Maxillofacial Prosthodontist',
  'Denturist',
  'Dental Hygienist',
  'Ceramist',
  'Implant Specialist',
  'Dental Ceramist',
  'Orthodontics & Dentofacial Orthopedics',
  'Registered Dental Hygienist',
  'Oral Surgeon',
  'Cosmetic & General Dentist',
  'Orthodontics',
  'Doctor of Dental Surgery',
  'Certified Orthotist',
  'Certified Prosthetist',
  'Certified Orthotist Prosthetist',
  'Orthotist & Prosthetist',
  'Cosmetic Ceramists',
  'General and Cosmetic Dentist',
];

export const Employees = [
  "1 to 10",
  "11 to 50",
  "51 to 200",
  "201 to 500",
  "501 to 1,000",
  "1,001 to 5,000",
  "5,001 to 10,000",
  "10,001+",
];

export const LocationType = ["Locations", "Headquarters"];
export const ProcedureCodes = [
  "D0120 Periodic Oral Evaluation - Established Patient",
  "D0140 Limited Oral Evaluation - Problem Focused",
  "D0145 Oral Evaluation For A Patient Under Three Years Of Age And Counseling With Primary Caregiver",
  "D0150 Comprehensive Oral Evaluation - New Or Established Patient",
  "D0160 Detailed And Extensive Oral Evaluation - Problem Focused, By Report",
  "D0170 Re-Evaluation - Limited, Problem Focused (Established Patient; Not Post-Operative Visit)",
  "D0171 Re-Evaluation – Post-Operative Office Visit",
  "D0180 Comprehensive Periodontal Evaluation - New Or Established Patient",
  "D0190 Screening Of A Patient",
  "D0191 Assessment Of A Patient",
  "D0210 Intraoral - Complete Series Of Radiographic Images",
  "D0220 Intraoral - Periapical First Radiographic Image",
  "D0230 Intraoral - Periapical Each Additional Radiographic Image",
  "D0240 Intraoral - Occlusal Radiographic Image",
  "D0250 Extra-Oral – 2D Projection Radiographic Image Created Using A Stationary Radiation Source, And Detector",
  "D0251 Extra-Oral Posterior Dental Radiographic Image",
  "D0270 Bitewing - Single Radiographic Image",
  "D0272 Bitewings - Two Radiographic Images",
  "D0273 Bitewings - Three Radiographic Images",
  "D0274 Bitewings - Four Radiographic Images",
  "D0277 Vertical Bitewings - 7 To 8 Radiographic Images",
  "D0310 Sialography",
  "D0320 Temporomandibular Joint Arthrogram, Including Injection",
  "D0321 Other Temporomandibular Joint Radiographic Images, By Report",
  "D0322 Tomographic Survey",
  "D0330 Panoramic Radiographic Image",
  "D0340 2D Cephalometric Radiographic Image – Acquisition, Measurement And Analysis",
  "D0350 2D Oral/Facial Photographic Image Obtained Intra-Orally Or Extra-Orally",
  "D0351 3D Photographic Image",
  "D0364 Cone Beam Ct Capture And Interpretation With Limited Field Of View – Less Than One Whole Jaw",
  "D0365 Cone Beam Ct Capture And Interpretation With Field Of View Of One Full Dental Arch – Mandible",
  "D0366 Cone Beam Ct Capture And Interpretation With Field Of View Of One Full Dental Arch – Maxilla, With Or Without Cranium",
  "D0367 Cone Beam Ct Capture And Interpretation With Field Of View Of Both Jaws; With Or Without Cranium",
  "D0368 Cone Beam Ct Capture And Interpretation For Tmj Series Including Two Or More Exposures",
  "D0369 Maxillofacial Mri Capture And Interpretation",
  "D0370 Maxillofacial Ultrasound Capture And Interpretation",
  "D0371 Sialoendoscopy Capture And Interpretation",
  "D0380 Cone Beam Ct Image Capture With Limited Field Of View – Less Than One Whole Jaw",
  "D0381 Cone Beam Ct Image Capture With Field Of View Of One Full Dental Arch – Mandible",
  "D0382 Cone Beam Ct Image Capture With Field Of View Of One Full Dental Arch – Maxilla, With Or Without Cranium",
  "D0383 Cone Beam Ct Image Capture With Field Of View Of Both Jaws; With Or Without Cranium",
  "D0384 Cone Beam Ct Image Capture For Tmj Series Including Two Or More Exposures",
  "D0385 Maxillofacial Mri Image Capture",
  "D0386 Maxillofacial Ultrasound Image Capture",
  "D0391 Interpretation Of Diagnostic Image By A Practitioner Not Associated With Capture Of The Image, Including Report",
  "D0393 Treatment Simulation Using 3D Image Volume",
  "D0394 Digital Subtraction Of Two Or More Images Or Image Volumes Of The Same Modality",
  "D0395 Fusion Of Two Or More 3D Image Volumes Of One Or More Modalities",
  "D0411 Hba1C In-Office Point Of Service Testing",
  "D0412 Blood Glucose Level Test – In-Office Using A Glucose Meter",
  "D0414 Laboratory Processing Of Microbial Specimen To Include Culture And Sensitivity Studies, Preparation And Transmission Of Written Report",
  "D0415 Collection Of Microorganisms For Culture And Sensitivity",
  "D0416 Viral Culture",
  "D0417 Collection And Preparation Of Saliva Sample For Laboratory Diagnostic Testing",
  "D0418 Analysis Of Saliva Sample",
  "D0419 Assessment Of Salivary Flow By Measurement",
  "D0422 Collection And Preparation Of Genetic Sample Material For Laboratory Analysis And Report",
  "D0423 Genetic Test For Susceptibility To Diseases – Specimen Analysis",
  "D0425 Caries Susceptibility Tests",
  "D0431 Adjunctive Pre-Diagnostic Test That Aids In Detection Of Mucosal Abnormalities Including Premalignant And Malignant Lesions, Not To Include Cytology Or Biopsy Procedures",
  "D0460 Pulp Vitality Tests",
  "D0470 Diagnostic Casts",
  "D0472 Accession Of Tissue, Gross Examination, Preparation And Transmission Of Written Report",
  "D0473 Accession Of Tissue, Gross And Microscopic Examination, Preparation And Transmission Of Written Report",
  "D0474 Accession Of Tissue, Gross And Microscopic Examination, Including Assessment Of Surgical Margins For Presence Of Disease, Preparation And Transmission Of Written Report",
  "D0475 Decalcification Procedure",
  "D0476 Special Stains For Microorganisms",
  "D0477 Special Stains, Not For Microorganisms",
  "D0478 Immunohistochemical Stains",
  "D0479 Tissue In-Situ Hybridization, Including Interpretation",
  "D0480 Accession Of Exfoliative Cytologic Smears, Microscopic Examination, Preparation And Transmission Of Written Report",
  "D0481 Electron Microscopy",
  "D0482 Direct Immunofluorescence",
  "D0483 Indirect Immunofluorescence",
  "D0484 Consultation On Slides Prepared Elsewhere",
  "D0485 Consultation, Including Preparation Of Slides From Biopsy Material Supplied By Referring Source",
  "D0486 Laboratory Accession Of Transepithelial Cytologic Sample, Microscopic Examination, Preparation And Transmission Of Written Report",
  "D0502 Other Oral Pathology Procedures, By Report",
  "D0600 Non-Ionizing Diagnostic Procedure Capable Of Quantifying,  Monitoring, And Recording Changes In Structure Of Enamel, Dentin, And Cementum",
  "D0601 Caries Risk Assessment And Documentation, With A Finding Of Low Risk",
  "D0602 Caries Risk Assessment And Documentation, With A Finding Of Moderate Risk",
  "D0603 Caries Risk Assessment And Documentation, With A Finding Of High Risk",
  "D0604 Antigen Testing For A Public Health Related Pathogen, Including Coronavirus",
  "D0605 Antibody Testing For A Public Health Related Pathogen, Including Coronavirus",
  "D0701 Panoramic Radiographic Image – Image Capture Only",
  "D0702 2-D Cephalometric Radiographic Image – Image Capture Only",
  "D0703 2-D Oral/Facial Photographic Image Obtained Intra-Orally Or Extra-Orally – Image Capture Only",
  "D0704 3-D Photographic Image – Image Capture Only",
  "D0705 Extra-Oral Posterior Dental Radiographic Image – Image Capture Only",
  "D0706 Intraoral – Occlusal Radiographic Image – Image Capture Only",
  "D0707 Intraoral – Periapical Radiographic Image – Image Capture Only",
  "D0708 Intraoral – Bitewing Radiographic Image – Image Capture Only",
  "D0709 Intraoral – Complete Series Of Radiographic Images – Image Capture Only",
  "D0999 Unspecified Diagnostic Procedure, By Report",
  "D1110 Prophylaxis - Adult",
  "D1120 Prophylaxis - Child",
  "D1206 Topical Application Of Fluoride Varnish",
  "D1208 Topical Application Of Fluoride – Excluding Varnish",
  "D1310 Nutritional Counseling For Control Of Dental Disease",
  "D1320 Tobacco Counseling For The Control And Prevention Of Oral Disease",
  "D1321 Counseling For The Control And Prevention Of Adverse Oral, Behavioral, And Systemic Health Effects Associated With High-Risk Substance Use",
  "D1330 Oral Hygiene Instructions",
  "D1351 Sealant - Per Tooth",
  "D1352 Preventive Resin Restoration In A Moderate To High Caries Risk Patient – Permanent Tooth",
  "D1353 Sealant Repair – Per Tooth",
  "D1354 Interim Caries Arresting Medicament Application – Per Tooth",
  "D1355 Caries Preventive Medicament Application – Per Tooth",
  "D1510 Space Maintainer - Fixed, Unilateral – Per Quadrant",
  "D1516 Space Maintainer - Fixed - Bilateral, Maxillary",
  "D1517 Space Maintainer - Fixed - Bilateral, Mandibular",
  "D1520 Space Maintainer - Removable, Unilateral - Per Quadrant",
  "D1526 Space Maintainer - Removable - Bilateral, Maxillary",
  "D1527 Space Maintainer - Removable - Bilateral, Mandibular",
  "D1551 Re-Cement Or Re-Bond Bilateral Space Maintainer - Maxillary",
  "D1552 Re-Cement Or Re-Bond Bilateral Space Maintainer - Mandibular",
  "D1553 Re-Cement Or Re-Bond Unilateral Space Maintainer - Per Quadrant",
  "D1556 Removal Of Fixed Unilateral Space Maintainer - Per Quadrant",
  "D1557 Removal Of Fixed Bilateral Space Maintainer - Maxillary",
  "D1558 Removal Of Fixed Bilateral Space Maintainer - Mandibular",
  "D1575 Distal Shoe Space Maintainer - Fixed, Unilateral - Per Quadrant",
  "D1999 Unspecified Preventive Procedure, By Report",
  "D2140 Amalgam - One Surface, Primary Or Permanent",
  "D2150 Amalgam - Two Surfaces, Primary Or Permanent",
  "D2160 Amalgam - Three Surfaces, Primary Or Permanent",
  "D2161 Amalgam - Four Or More Surfaces, Primary Or Permanent",
  "D2330 Resin-Based Composite - One Surface, Anterior",
  "D2331 Resin-Based Composite - Two Surfaces, Anterior",
  "D2332 Resin-Based Composite - Three Surfaces, Anterior",
  "D2335 Resin-Based Composite - Four Or More Surfaces Or Involving Incisal Angle (Anterior)",
  "D2390 Resin-Based Composite Crown, Anterior",
  "D2391 Resin-Based Composite - One Surface, Posterior",
  "D2392 Resin-Based Composite - Two Surfaces, Posterior",
  "D2393 Resin-Based Composite - Three Surfaces, Posterior",
  "D2394 Resin-Based Composite - Four Or More Surfaces, Posterior",
  "D2410 Gold Foil - One Surface",
  "D2420 Gold Foil - Two Surfaces",
  "D2430 Gold Foil - Three Surfaces",
  "D2510 Inlay - Metallic - One Surface",
  "D2520 Inlay - Metallic - Two Surfaces",
  "D2530 Inlay - Metallic - Three Or More Surfaces",
  "D2542 Onlay - Metallic - Two Surfaces",
  "D2543 Onlay - Metallic - Three Surfaces",
  "D2544 Onlay - Metallic - Four Or More Surfaces",
  "D2610 Inlay - Porcelain/Ceramic - One Surface",
  "D2620 Inlay - Porcelain/Ceramic - Two Surfaces",
  "D2630 Inlay - Porcelain/Ceramic - Three Or More Surfaces",
  "D2642 Onlay - Porcelain/Ceramic - Two Surfaces",
  "D2643 Onlay - Porcelain/Ceramic - Three Surfaces",
  "D2644 Onlay - Porcelain/Ceramic - Four Or More Surfaces",
  "D2650 Inlay - Resin-Based Composite - One Surface",
  "D2651 Inlay - Resin-Based Composite - Two Surfaces",
  "D2652 Inlay - Resin-Based Composite - Three Or More Surfaces",
  "D2662 Onlay - Resin-Based Composite - Two Surfaces",
  "D2663 Onlay - Resin-Based Composite - Three Surfaces",
  "D2664 Onlay - Resin-Based Composite - Four Or More Surfaces",
  "D2710 Crown - Resin-Based Composite (Indirect)",
  "D2712 Crown - ¾ Resin-Based Composite (Indirect)",
  "D2720 Crown - Resin With High Noble Metal",
  "D2721 Crown - Resin With Predominantly Base Metal",
  "D2722 Crown - Resin With Noble Metal",
  "D2740 Crown - Porcelain/Ceramic",
  "D2750 Crown - Porcelain Fused To High Noble Metal",
  "D2751 Crown - Porcelain Fused To Predominantly Base Metal",
  "D2752 Crown - Porcelain Fused To Noble Metal",
  "D2753 Crown - Porcelain Fused To Titanium And Titanium Alloys",
  "D2780 Crown - 3/4 Cast High Noble Metal",
  "D2781 Crown - 3/4 Cast Predominantly Base Metal",
  "D2782 Crown - 3/4 Cast Noble Metal",
  "D2783 Crown - 3/4 Porcelain/Ceramic",
  "D2790 Crown - Full Cast High Noble Metal",
  "D2791 Crown - Full Cast Predominantly Base Metal",
  "D2792 Crown - Full Cast Noble Metal",
  "D2794 Crown - Titanium And Titanium Alloys",
  "D2799 Provisional Crown– Further Treatment Or Completion Of Diagnosis Necessary Prior To Final Impression",
  "D2910 Re-Cement Or Re-Bond Inlay, Onlay, Veneer Or Partial Coverage Restoration",
  "D2915 Re-Cement Or Re-Bond Indirectly Fabricated Or Prefabricated Post And Core",
  "D2920 Re-Cement Or Re-Bond Crown",
  "D2921 Reattachment Of Tooth Fragment, Incisal Edge Or Cusp",
  "D2928 Prefabricated Porcelain/Ceramic Crown – Permanent Tooth",
  "D2929 Prefabricated Porcelain/Ceramic Crown – Primary Tooth",
  "D2930 Prefabricated Stainless Steel Crown - Primary Tooth",
  "D2931 Prefabricated Stainless Steel Crown - Permanent Tooth",
  "D2932 Prefabricated Resin Crown",
  "D2933 Prefabricated Stainless Steel Crown With Resin Window",
  "D2934 Prefabricated Esthetic Coated Stainless Steel Crown - Primary Tooth",
  "D2940 Protective Restoration",
  "D2941 Interim Therapeutic Restoration – Primary Dentition",
  "D2949 Restorative Foundation For An Indirect Restoration",
  "D2950 Core Buildup, Including Any Pins When Required",
  "D2951 Pin Retention - Per Tooth, In Addition To Restoration",
  "D2952 Post And Core In Addition To Crown, Indirectly Fabricated",
  "D2953 Each Additional Indirectly Fabricated Post - Same Tooth",
  "D2954 Prefabricated Post And Core In Addition To Crown",
  "D2955 Post Removal",
  "D2957 Each Additional Prefabricated Post - Same Tooth",
  "D2960 Labial Veneer (Resin Laminate) - Direct",
  "D2961 Labial Veneer (Resin Laminate) - Indirect",
  "D2962 Labial Veneer (Porcelain Laminate) - Indirect",
  "D2971 Additional Procedures To Construct New Crown Under Existing Partial Denture Framework",
  "D2975 Coping",
  "D2980 Crown Repair Necessitated By Restorative Material Failure",
  "D2981 Inlay Repair Necessitated By Restorative Material Failure",
  "D2982 Onlay Repair Necessitated By Restorative Material Failure",
  "D2983 Veneer Repair Necessitated By Restorative Material Failure",
  "D2990 Resin Infiltration Of Incipient Smooth Surface Lesions",
  "D2999 Unspecified Restorative Procedure, By Report",
  "D3110 Pulp Cap - Direct (Excluding Final Restoration)",
  "D3120 Pulp Cap - Indirect (Excluding Final Restoration)",
  "D3220 Therapeutic Pulpotomy (Excluding Final Restoration) - Removal Of Pulp Coronal To The Dentinocemental Junction And Application Of Medicament",
  "D3221 Pulpal Debridement, Primary And Permanent Teeth",
  "D3222 Partial Pulpotomy For Apexogenesis - Permanent Tooth With Incomplete Root Development",
  "D3230 Pulpal Therapy (Resorbable Filling) - Anterior, Primary Tooth (Excluding Final Restoration)",
  "D3240 Pulpal Therapy (Resorbable Filling) - Posterior, Primary Tooth (Excluding Final Restoration)",
  "D3310 Endodontic Therapy, Anterior Tooth (Excluding Final Restoration)",
  "D3320 Endodontic Therapy, Premolar Tooth (Excluding Final Restoration)",
  "D3330 Endodontic Therapy, Molar Tooth (Excluding Final Restoration)",
  "D3331 Treatment Of Root Canal Obstruction; Non-Surgical Access",
  "D3332 Incomplete Endodontic Therapy; Inoperable, Unrestorable Or Fractured Tooth",
  "D3333 Internal Root Repair Of Perforation Defects",
  "D3346 Retreatment Of Previous Root Canal Therapy - Anterior",
  "D3347 Retreatment Of Previous Root Canal Therapy - Premolar",
  "D3348 Retreatment Of Previous Root Canal Therapy - Molar",
  "D3351 Apexification/Recalcification – Initial Visit (Apical Closure/Calcific Repair Of Perforations, Root Resorption, Etc.)",
  "D3352 Apexification/Recalcification – Interim Medication Replacement",
  "D3353 Apexification/Recalcification - Final Visit (Includes Completed Root Canal Therapy - Apical Closure/Calcific Repair Of Perforations, Root Resorption, Etc.)",
  "D3355 Pulpal Regeneration - Initial Visit",
  "D3356 Pulpal Regeneration - Interim Medication Replacement",
  "D3357 Pulpal Regeneration - Completion Of Treatment",
  "D3410 Apicoectomy - Anterior",
  "D3421 Apicoectomy - Premolar (First Root)",
  "D3425 Apicoectomy - Molar (First Root)",
  "D3426 Apicoectomy (Each Additional Root)",
  "D3427 Periradicular Surgery Without Apicoectomy",
  "D3428 Bone Graft In Conjunction With Periradicular Surgery – Per Tooth, Single Site",
  "D3429 Bone Graft In Conjunction With Periradicular Surgery – Each Additional Contiguous Tooth In The Same Surgical Site",
  "D3430 Retrograde Filling - Per Root",
  "D3431 Biologic Materials To Aid In Soft And Osseous Tissue Regeneration In Conjunction With Periradicular Surgery",
  "D3432 Guided Tissue Regeneration, Resorbable Barrier, Per Site, In Conjunction With Periradicular Surgery",
  "D3450 Root Amputation - Per Root",
  "D3460 Endodontic Endosseous Implant",
  "D3470 Intentional Re-Implantation (Including Necessary Splinting)",
  "D3471 Surgical Repair Of Root Resorption - Anterior",
  "D3472 Surgical Repair Of Root Resorption – Premolar",
  "D3473 Surgical Repair Of Root Resorption – Molar",
  "D3501 Surgical Exposure Of Root Surface Without Apicoectomy Or Repair Of Root Resorption – Anterior",
  "D3502 Surgical Exposure Of Root Surface Without Apicoectomy Or Repair Of Root Resorption – Premolar",
  "D3503 Surgical Exposure Of Root Surface Without Apicoectomy Or Repair Of Root Resorption – Molar",
  "D3910 Surgical Procedure For Isolation Of Tooth With Rubber Dam",
  "D3920 Hemisection (Including Any Root Removal), Not Including Root Canal Therapy",
  "D3950 Canal Preparation And Fitting Of Preformed Dowel Or Post",
  "D3999 Unspecified Endodontic Procedure, By Report",
  "D4210 Gingivectomy Or Gingivoplasty - Four Or More Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4211 Gingivectomy Or Gingivoplasty - One To Three Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4212 Gingivectomy Or Gingivoplasty To Allow Access For Restorative Procedure, Per Tooth",
  "D4230 Anatomical Crown Exposure – Four Or More Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4231 Anatomical Crown Exposure – One To Three Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4240 Gingival Flap Procedure, Including Root Planing - Four Or More Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4241 Gingival Flap Procedure, Including Root Planing - One To Three Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4245 Apically Positioned Flap",
  "D4249 Clinical Crown Lengthening – Hard Tissue",
  "D4260 Osseous Surgery (Including Elevation Of A Full Thickness Flap And Closure) – Four Or More Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4261 Osseous Surgery (Including Elevation Of A Full Thickness Flap And Closure) – One To Three Contiguous Teeth Or Tooth Bounded Spaces Per Quadrant",
  "D4263 Bone Replacement Graft – Retained Natural Tooth – First Site In Quadrant",
  "D4264 Bone Replacement Graft – Retained Natural Tooth – Each Additional Site In Quadrant",
  "D4265 Biologic Materials To Aid In Soft And Osseous Tissue Regeneration",
  "D4266 Guided Tissue Regeneration - Resorbable Barrier, Per Site",
  "D4267 Guided Tissue Regeneration - Nonresorbable Barrier, Per Site (Includes Membrane Removal)",
  "D4268 Surgical Revision Procedure, Per Tooth",
  "D4270 Pedicle Soft Tissue Graft Procedure",
  "D4273 Autogenous Connective Tissue Graft Procedure (Including Donor And Recipient Surgical Sites) First Tooth, Implant, Or Edentulous Tooth Position In Graft",
  "D4274 Mesial/Distal Wedge Procedure, Single Tooth (When Not Performed In Conjunction With Surgical Procedures In The Same Anatomical Area)",
  "D4275 Non-Autogenous Connective Tissue Graft (Including Recipient Site And Donor Material) First Tooth, Implant, Or Edentulous Tooth Position In Graft",
  "D4276 Combined Connective Tissue And Double Pedicle Graft, Per Tooth",
  "D4277 Free Soft Tissue Graft Procedure (Including Recipient And Donor Surgical Sites) First Tooth, Implant Or Edentulous Tooth Position In Graft",
  "D4278 Free Soft Tissue Graft Procedure (Including Recipient And Donor Surgical Sites) Each Additional Contiguous Tooth, Implant Or Edentulous Tooth Position In Same Graft Site",
  "D4283 Autogenous Connective Tissue Graft Procedure (Including Donor And Recipient Surgical Sites) – Each Additional Contiguous Tooth, Implant Or Edentulous Tooth Position In Same Graft Site",
  "D4285 Non-Autogenous Connective Tissue Graft Procedure (Including Recipient Surgical Site And Donor Material) – Each Additional Contiguous Tooth, Implant Or Edentulous Tooth Position In Same Graft Site",
  "D4320 Provisional Splinting - Intracoronal",
  "D4321 Provisional Splinting - Extracoronal",
  "D4341 Periodontal Scaling And Root Planing - Four Or More Teeth Per Quadrant",
  "D4342 Periodontal Scaling And Root Planing - One To Three Teeth Per Quadrant",
  "D4346 Scaling In Presence Of Generalized Moderate Or Severe Gingival Inflammation – Full Mouth, After Oral Evaluation",
  "D4355 Full Mouth Debridement To Enable A Comprehensive Oral Evaluation And Diagnosis On A Subsequent Visit",
  "D4381 Localized Delivery Of Antimicrobial Agents Via A Controlled Release Vehicle Into Diseased Crevicular Tissue, Per Tooth",
  "D4910 Periodontal Maintenance",
  "D4920 Unscheduled Dressing Change (By Someone Other Than Treating Dentist Or Their Staff)",
  "D4921 Gingival Irrigation – Per Quadrant",
  "D4999 Unspecified Periodontal Procedure, By Report",
  "D5110 Complete Denture - Maxillary",
  "D5120 Complete Denture - Mandibular",
  "D5130 Immediate Denture - Maxillary",
  "D5140 Immediate Denture - Mandibular",
  "D5211 Maxillary Partial Denture – Resin Base (Including, Retentive/Clasping Materials, Rests, And Teeth)",
  "D5212 Mandibular Partial Denture – Resin Base (Including, Retentive/Clasping Materials, Rests, And Teeth)",
  "D5213 Maxillary Partial Denture - Cast Metal Framework With Resin Denture Bases (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5214 Mandibular Partial Denture - Cast Metal Framework With Resin Denture Bases (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5221 Immediate Maxillary Partial Denture - Resin Base (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5222 Immediate Mandibular Partial Denture - Resin Base (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5223 Immediate Maxillary Partial Denture - Cast Metal Framework With Resin Denture Bases (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5224 Immediate Mandibular Partial Denture - Cast Metal Framework With Resin Denture Bases (Including Retentive/Clasping Materials, Rests And Teeth)",
  "D5225 Maxillary Partial Denture - Flexible Base (Including Retentive/Clasping Materials, Rests, And Teeth)",
  "D5226 Mandibular Partial Denture - Flexible Base (Including Retentive/Clasping Materials, Rests, And Teeth)",
  "D5282 Removable Unilateral Partial Denture – One Piece Cast Metal (Including Retentive/Clasping Materials, Rests, And Teeth), Maxillary",
  "D5283 Removable Unilateral Partial Denture – One Piece Cast Metal (Including Rententive/Clasping Materias, Rests, And Teeth), Mandibular",
  "D5284 Removable Unilateral Partial Denture – One Piece Flexible Base (Including Retentive/Clasping Materials, Rests, And Teeth) – Per Quadrant",
  "D5286 Removable Unilateral Partial Denture – One Piece Resin (Including Retentive/Clasping Materials, Rests, And Teeth) – Per Quadrant",
  "D5410 Adjust Complete Denture - Maxillary",
  "D5411 Adjust Complete Denture - Mandibular",
  "D5421 Adjust Partial Denture - Maxillary",
  "D5422 Adjust Partial Denture - Mandibular",
  "D5511 Repair Broken Complete Denture Base, Mandibular",
  "D5512 Repair Broken Complete Denture Base, Maxillary",
  "D5520 Replace Missing Or Broken Teeth - Complete Denture (Each Tooth)",
  "D5611 Repair Resin Partial Denture Base, Mandibular",
  "D5612 Repair Resin Partial Denture Base, Maxillary",
  "D5621 Repair Cast Partial Framework, Mandibular",
  "D5622 Repair Cast Partial Framework, Maxillary",
  "D5630 Repair Or Replace Broken Retentive Clasping Materials – Per Tooth",
  "D5640 Replace Broken Teeth - Per Tooth",
  "D5650 Add Tooth To Existing Partial Denture",
  "D5660 Add Clasp To Existing Partial Denture - Per Tooth",
  "D5670 Replace All Teeth And Acrylic On Cast Metal Framework (Maxillary)",
  "D5671 Replace All Teeth And Acrylic On Cast Metal Framework (Mandibular)",
  "D5710 Rebase Complete Maxillary Denture",
  "D5711 Rebase Complete Mandibular Denture",
  "D5720 Rebase Maxillary Partial Denture",
  "D5721 Rebase Mandibular Partial Denture",
  "D5730 Reline Complete Maxillary Denture (Direct)",
  "D5731 Reline Complete Mandibular Denture (Direct)",
  "D5740 Reline Maxillary Partial Denture (Direct)",
  "D5741 Reline Mandibular Partial Denture (Direct)",
  "D5750 Reline Complete Maxillary Denture (Indirect)",
  "D5751 Reline Complete Mandibular Denture (Indirect)",
  "D5760 Reline Maxillary Partial Denture (Indirect)",
  "D5761 Reline Mandibular Partial Denture (Indirect)",
  "D5810 Interim Complete Denture (Maxillary)",
  "D5811 Interim Complete Denture (Mandibular)",
  "D5820 Interim Partial Denture (Including Retentive/Clasping Materials, Rests, And Teeth), Maxillary",
  "D5821 Interim Partial Denture (Including Retentive/Clasping Materials, Rests, And Teeth), Mandibular",
  "D5850 Tissue Conditioning, Maxillary",
  "D5851 Tissue Conditioning, Mandibular",
  "D5862 Precision Attachment, By Report",
  "D5863 Overdenture – Complete Maxillary",
  "D5864 Overdenture – Partial Maxillary",
  "D5865 Overdenture – Complete Mandibular",
  "D5866 Overdenture – Partial Mandibular",
  "D5867 Replacement Of Replaceable Part Of Semi-Precision Or Precision Attachment (Male Or Female Component)",
  "D5875 Modification Of Removable Prosthesis Following Implant Surgery",
  "D5876 Add Metal Substructure To Acrylic Full Denture (Per Arch)",
  "D5899 Unspecified Removable Prosthodontic Procedure, By Report",
  "D5911 Facial Moulage (Sectional)",
  "D5912 Facial Moulage (Complete)",
  "D5913 Nasal Prosthesis",
  "D5914 Auricular Prosthesis",
  "D5915 Orbital Prosthesis",
  "D5916 Ocular Prosthesis",
  "D5919 Facial Prosthesis",
  "D5922 Nasal Septal Prosthesis",
  "D5923 Ocular Prosthesis, Interim",
  "D5924 Cranial Prosthesis",
  "D5925 Facial Augmentation Implant Prosthesis",
  "D5926 Nasal Prosthesis, Replacement",
  "D5927 Auricular Prosthesis, Replacement",
  "D5928 Orbital Prosthesis, Replacement",
  "D5929 Facial Prosthesis, Replacement",
  "D5931 Obturator Prosthesis, Surgical",
  "D5932 Obturator Prosthesis, Definitive",
  "D5933 Obturator Prosthesis, Modification",
  "D5934 Mandibular Resection Prosthesis With Guide Flange",
  "D5935 Mandibular Resection Prosthesis Without Guide Flange",
  "D5936 Obturator Prosthesis, Interim",
  "D5937 Trismus Appliance (Not For Tmd Treatment)",
  "D5951 Feeding Aid",
  "D5952 Speech Aid Prosthesis, Pediatric",
  "D5953 Speech Aid Prosthesis, Adult",
  "D5954 Palatal Augmentation Prosthesis",
  "D5955 Palatal Lift Prosthesis, Definitive",
  "D5958 Palatal Lift Prosthesis, Interim",
  "D5959 Palatal Lift Prosthesis, Modification",
  "D5960 Speech Aid Prosthesis, Modification",
  "D5982 Surgical Stent",
  "D5983 Radiation Carrier",
  "D5984 Radiation Shield",
  "D5985 Radiation Cone Locator",
  "D5986 Fluoride Gel Carrier",
  "D5987 Commissure Splint",
  "D5988 Surgical Splint",
  "D5991 Vesiculobullous Disease Medicament Carrier",
  "D5992 Adjust Maxillofacial Prosthetic Appliance, By Report",
  "D5993 Maintenance And Cleaning Of A Maxillofacial Prosthesis (Extra- Or Intra-Oral) Other Than Required Adjustments, By Report",
  "D5994 Periodontal Medicament Carrier With Peripheral Seal – Laboratory Processed",
  "D5995 Periodontal Medicament Carrier With Peripheral Seal – Laboratory Processed – Maxillary",
  "D5996 Periodontal Medicament Carrier With Peripheral Seal – Laboratory Processed – Mandibular",
  "D5999 Unspecified Maxillofacial Prosthesis, By Report",
  "D6010 Surgical Placement Of Implant Body: Endosteal Implant",
  "D6011 Surgical Access To An Implant Body (Second Stage Implant Surgery)",
  "D6012 Surgical Placement Of Interim Implant Body For Transitional Prosthesis: Endosteal Implant",
  "D6013 Surgical Placement Of Mini Implant",
  "D6040 Surgical Placement: Eposteal Implant",
  "D6050 Surgical Placement: Transosteal Implant",
  "D6051 Interim Abutment",
  "D6052 Semi-Precision Attachment Abutment",
  "D6055 Connecting Bar – Implant Supported Or Abutment Supported",
  "D6056 Prefabricated Abutment – Includes Modification And Placement",
  "D6057 Custom Fabricated Abutment – Includes Placement",
  "D6058 Abutment Supported Porcelain/Ceramic Crown",
  "D6059 Abutment Supported Porcelain Fused To Metal Crown (High Noble Metal)",
  "D6060 Abutment Supported Porcelain Fused To Metal Crown (Predominantly Base Metal)",
  "D6061 Abutment Supported Porcelain Fused To Metal Crown (Noble Metal)",
  "D6062 Abutment Supported Cast Metal Crown (High Noble Metal)",
  "D6063 Abutment Supported Cast Metal Crown (Predominantly Base Metal)",
  "D6064 Abutment Supported Cast Metal Crown (Noble Metal)",
  "D6065 Implant Supported Porcelain/Ceramic Crown",
  "D6066 Implant Supported Crown - Porcelain Fused To High Noble Alloys",
  "D6067 Implant Supported Crown - High Noble Alloys",
  "D6068 Abutment Supported Retainer For Porcelain/Ceramic Fpd",
  "D6069 Abutment Supported Retainer For Porcelain Fused To Metal Fpd (High Noble Metal)",
  "D6070 Abutment Supported Retainer For Porcelain Fused To Metal Fpd (Predominantly Base Metal)",
  "D6071 Abutment Supported Retainer For Porcelain Fused To Metal Fpd (Noble Metal)",
  "D6072 Abutment Supported Retainer For Cast Metal Fpd (High Noble Metal)",
  "D6073 Abutment Supported Retainer For Cast Metal Fpd (Predominantly Base Metal)",
  "D6074 Abutment Supported Retainer For Cast Metal Fpd (Noble Metal)",
  "D6075 Implant Supported Retainer For Ceramic Fpd",
  "D6076 Implant Supported Retainer For Fpd - Porcelain Fused To High Noble Alloys",
  "D6077 Implant Supported Retainer For Metal Fpd - High Noble Alloys",
  "D6080 Implant Maintenance Procedures When Prostheses Are Removed And Reinserted, Including Cleansing Of Prostheses And Abutments",
  "D6081 Scaling And Debridement In The Presence Of Inflammation Or Mucositis Of A Single Implant, Including Cleaning Of The Implant Surfaces, Without Flap Entry And Closure",
  "D6082 Implant Supported Crown - Porcelain Fused To Predominantly Base Alloys",
  "D6083 Implant Supported Crown - Porcelain Fused To Noble Alloys",
  "D6084 Implant Supported Crown - Porcelain Fused To Titanium And Titanium Alloys",
  "D6085 Provisional Implant Crown",
  "D6086 Implant Supported Crown - Predominantly Base Alloys",
  "D6087 Implant Supported Crown - Noble Alloys",
  "D6088 Implant Supported Crown - Titanium And Titanium Alloys",
  "D6090 Repair Implant Supported Prosthesis, By Report",
  "D6091 Replacement Of Replaceable Part Of Semi-Precision Or Precision Attachment (Male Or Female Component) Of Implant/Abutment Supported Prosthesis, Per Attachment",
  "D6092 Re-Cement Or Re-Bond Implant/Abutment Supported Crown",
  "D6093 Re-Cement Or Re-Bond Implant/Abutment Supported Fixed Partial Denture",
  "D6094 Abutment Supported Crown - Titanium And Titanium Alloys",
  "D6095 Repair Implant Abutment, By Report",
  "D6096 Remove Broken Implant Retaining Screw",
  "D6097 Abutment Supported Crown - Porcelain Fused To Titanium And Titanium Alloys",
  "D6098 Implant Supported Retainer - Porcelain Fused To Predominantly Base Alloys",
  "D6099 Implant Supported Retainer For Fpd - Porcelain Fused To Noble Alloys",
  "D6100 Implant Removal, By Report",
  "D6101 Debridement Of A Peri-Implant Defect Or Defects Surrounding A Single Implant, And Surface Cleaning Of The Exposed Implant Surfaces, Including Flap Entry And Closure",
  "D6102 Debridement And Osseous Contouring Of A Peri-Implant Defect Or Defects Surrounding A Single Implant And Includes Surface Cleaning Of The Exposed Implant Surfaces, Including Flap Entry And Closure ",
  "D6103 Bone Graft For Repair Of Peri-Implant Defect – Does Not Include Flap Entry And Closure",
  "D6104 Bone Graft At Time Of Implant Placement",
  "D6110 Implant /Abutment Supported Removable Denture For Edentulous Arch – Maxillary",
  "D6111 Implant /Abutment Supported Removable Denture For Edentulous Arch – Mandibular",
  "D6112 Implant /Abutment Supported Removable Denture For Partially Edentulous Arch – Maxillary",
  "D6113 Implant /Abutment Supported Removable Denture For Partially Edentulous Arch – Mandibular",
  "D6114 Implant /Abutment Supported Fixed Denture For Edentulous Arch – Maxillary",
  "D6115 Implant /Abutment Supported Fixed Denture For Edentulous Arch – Mandibular",
  "D6116 Implant /Abutment Supported Fixed Denture For Partially Edentulous Arch – Maxillary",
  "D6117 Implant /Abutment Supported Fixed Denture For Partially Edentulous Arch – Mandibular",
  "D6118 Implant/Abutment Supported Interim Fixed Denture For Edentulous Arch – Mandibular",
  "D6119 Implant/Abutment Supported Interim Fixed Denture For Edentulous Arch – Maxillary",
  "D6120 Implant Supported Retainer – Porcelain Fused To Titanium And Titanium Alloys",
  "D6121 Implant Supported Retainer For Metal Fpd – Predominantly Base Alloys",
  "D6122 Implant Supported Retainer For Metal Fpd – Noble Alloys",
  "D6123 Implant Supported Retainer For Metal Fpd – Titanium And Titanium Alloys",
  "D6190 Radiographic/Surgical Implant Index, By Report",
  "D6191 Semi-Precision Abutment – Placement",
  "D6192 Semi-Precision Attachment – Placement",
  "D6194 Abutment Supported Retainer Crown For Fpd – Titanium And Titanium Alloys",
  "D6195 Abutment Supported Retainer - Porcelain Fused To Titanium And Titanium Alloys",
  "D6199 Unspecified Implant Procedure, By Report",
  "D6205 Pontic - Indirect Resin Based Composite",
  "D6210 Pontic - Cast High Noble Metal",
  "D6211 Pontic - Cast Predominantly Base Metal",
  "D6212 Pontic - Cast Noble Metal",
  "D6214 Pontic - Titanium And Titanium Alloys",
  "D6240 Pontic - Porcelain Fused To High Noble Metal",
  "D6241 Pontic - Porcelain Fused To Predominantly Base Metal",
  "D6242 Pontic - Porcelain Fused To Noble Metal",
  "D6243 Pontic - Porcelain Fused To Titanium And Titanium Alloys",
  "D6245 Pontic - Porcelain/Ceramic",
  "D6250 Pontic - Resin With High Noble Metal",
  "D6251 Pontic - Resin With Predominantly Base Metal",
  "D6252 Pontic - Resin With Noble Metal",
  "D6253 Provisional Pontic - Further Treatment Or Completion Of Diagnosis Necessary Prior To Final  Impression",
  "D6545 Retainer - Cast Metal For Resin Bonded Fixed Prosthesis",
  "D6548 Retainer - Porcelain/Ceramic For Resin Bonded Fixed Prosthesis",
  "D6549 Retainer – For Resin Bonded Fixed Prosthesis",
  "D6600 Retainer Inlay - Porcelain/Ceramic, Two Surfaces",
  "D6601 Retainer Inlay - Porcelain/Ceramic, Three Or More Surfaces",
  "D6602 Retainer Inlay - Cast High Noble Metal, Two Surfaces",
  "D6603 Retainer Inlay - Cast High Noble Metal, Three Or More Surfaces",
  "D6604 Retainer Inlay - Cast Predominantly Base Metal, Two Surfaces",
  "D6605 Retainer Inlay - Cast Predominantly Base Metal, Three Or More Surfaces",
  "D6606 Retainer Inlay - Cast Noble Metal, Two Surfaces",
  "D6607 Retainer Inlay - Cast Noble Metal, Three Or More Surfaces",
  "D6608 Retainer Onlay - Porcelain/Ceramic, Two Surfaces",
  "D6609 Retainer Onlay - Porcelain/Ceramic, Three Or More Surfaces",
  "D6610 Retainer Onlay - Cast High Noble Metal, Two Surfaces",
  "D6611 Retainer Onlay - Cast High Noble Metal, Three Or More Surfaces",
  "D6612 Retainer Onlay - Cast Predominantly Base Metal, Two Surfaces",
  "D6613 Retainer Onlay - Cast Predominantly Base Metal, Three Or More Surfaces",
  "D6614 Retainer Onlay - Cast Noble Metal, Two Surfaces",
  "D6615 Retainer Onlay - Cast Noble Metal, Three Or More Surfaces",
  "D6624 Retainer Inlay - Titanium",
  "D6634 Retainer Onlay - Titanium",
  "D6710 Retainer Crown - Indirect Resin Based Composite",
  "D6720 Retainer Crown - Resin With High Noble Metal",
  "D6721 Retainer Crown - Resin With Predominantly Base Metal",
  "D6722 Retainer Crown - Resin With Noble Metal",
  "D6740 Retainer Crown - Porcelain/Ceramic",
  "D6750 Retainer Crown - Porcelain Fused To High Noble Metal",
  "D6751 Retainer Crown - Porcelain Fused To Predominantly Base Metal",
  "D6752 Retainer Crown - Porcelain Fused To Noble Metal",
  "D6753 Retainer Crown - Porcelain Fused To Titanium And Titanium Alloys",
  "D6780 Retainer Crown - 3/4 Cast High Noble Metal",
  "D6781 Retainer Crown - 3/4 Cast Predominantly Base Metal",
  "D6782 Retainer Crown - 3/4 Cast Noble Metal",
  "D6783 Retainer Crown - 3/4 Porcelain/Ceramic",
  "D6784 Retainer Crown ¾ - Titanium And Titanium Alloys",
  "D6790 Retainer Crown - Full Cast High Noble Metal",
  "D6791 Retainer Crown - Full Cast Predominantly Base Metal",
  "D6792 Retainer Crown - Full Cast Noble Metal",
  "D6793 Provisional Retainer Crown - Further Treatment Or Completion Of Diagnosis Necessary Prior To Final Impression",
  "D6794 Retainer Crown - Titanium And Titanium Alloys",
  "D6920 Connector Bar",
  "D6930 Re-Cement Or Re-Bond Fixed Partial Denture",
  "D6940 Stress Breaker",
  "D6950 Precision Attachment",
  "D6980 Fixed Partial Denture Repair Necessitated By Restorative Material Failure",
  "D6985 Pediatric Partial Denture, Fixed",
  "D6999 Unspecified Fixed Prosthodontic Procedure, By Report",
  "D7111 Extraction, Coronal Remnants – Primary Tooth",
  "D7140 Extraction, Erupted Tooth Or Exposed Root (Elevation And/Or Forceps Removal)",
  "D7210 Extraction, Erupted Tooth Requiring Removal Of Bone And/Or Sectioning Of Tooth, And Including Elevation Of Mucoperiosteal Flap If Indicated",
  "D7220 Removal Of Impacted Tooth - Soft Tissue",
  "D7230 Removal Of Impacted Tooth - Partially Bony",
  "D7240 Removal Of Impacted Tooth - Completely Bony",
  "D7241 Removal Of Impacted Tooth - Completely Bony, With Unusual Surgical Complications",
  "D7250 Removal Of Residual Tooth Roots (Cutting Procedure)",
  "D7251 Coronectomy – Intentional Partial Tooth Removal",
  "D7260 Oroantral Fistula Closure",
  "D7261 Primary Closure Of A Sinus Perforation",
  "D7270 Tooth Re-Implantation And/Or Stabilization Of Accidentally Evulsed Or Displaced Tooth",
  "D7272 Tooth Transplantation (Includes Re-Implantation From One Site To Another And Splinting And/Or Stabilization)",
  "D7280 Exposure Of An Unerupted Tooth",
  "D7282 Mobilization Of Erupted Or Malpositioned Tooth To Aid Eruption",
  "D7283 Placement Of Device To Facilitate Eruption Of Impacted Tooth",
  "D7285 Incisional Biopsy Of Oral Tissue-Hard (Bone, Tooth)",
  "D7286 Incisional Biopsy Of Oral Tissue-Soft",
  "D7287 Exfoliative Cytological Sample Collection",
  "D7288 Brush Biopsy - Transepithelial Sample Collection",
  "D7290 Surgical Repositioning Of Teeth",
  "D7291 Transseptal Fiberotomy/Supra Crestal Fiberotomy, By Report",
  "D7292 Placement Of Temporary Anchorage Device [Screw Retained Plate] Requiring Flap; Includes Device Removal",
  "D7293 Placement Of Temporary Anchorage Device Requiring Flap; Includes Device Removal",
  "D7294 Placement Of Temporary Anchorage Device Without Flap; Includes Device Removal",
  "D7295 Harvest Of Bone For Use In Autogenous Grafting Procedure",
  "D7296 Corticotomy – One To Three Teeth Or Tooth Spaces, Per Quadrant",
  "D7297 Corticotomy – Four Or More Teeth Or Tooth Spaces, Per Quadrant",
  "D7310 Alveoloplasty In Conjunction With Extractions - Four Or More Teeth Or Tooth Spaces, Per Quadrant",
  "D7311 Alveoloplasty In Conjunction With Extractions - One To Three Teeth Or Tooth Spaces, Per Quadrant",
  "D7320 Alveoloplasty Not In Conjunction With Extractions - Four Or More Teeth Or Tooth Spaces, Per Quadrant",
  "D7321 Alveoloplasty Not In Conjunction With Extractions - One To Three Teeth Or Tooth Spaces, Per Quadrant",
  "D7340 Vestibuloplasty - Ridge Extension (Secondary Epithelialization)",
  "D7350 Vestibuloplasty - Ridge Extension (Including Soft Tissue Grafts, Muscle Reattachment, Revision Of Soft Tissue Attachment And Management Of Hypertrophied And Hyperplastic Tissue)",
  "D7410 Excision Of Benign Lesion Up To 1.25 Cm",
  "D7411 Excision Of Benign Lesion Greater Than 1.25 Cm",
  "D7412 Excision Of Benign Lesion, Complicated",
  "D7413 Excision Of Malignant Lesion Up To 1.25 Cm",
  "D7414 Excision Of Malignant Lesion Greater Than 1.25 Cm",
  "D7415 Excision Of Malignant Lesion, Complicated",
  "D7440 Excision Of Malignant Tumor - Lesion Diameter Up To 1.25 Cm",
  "D7441 Excision Of Malignant Tumor - Lesion Diameter Greater Than 1.25 Cm",
  "D7450 Removal Of Benign Odontogenic Cyst Or Tumor - Lesion Diameter Up To 1.25 Cm",
  "D7451 Removal Of Benign Odontogenic Cyst Or Tumor - Lesion Diameter Greater Than 1.25 Cm",
  "D7460 Removal Of Benign Nonodontogenic Cyst Or Tumor - Lesion Diameter Up To 1.25 Cm",
  "D7461 Removal Of Benign Nonodontogenic Cyst Or Tumor - Lesion Diameter Greater Than 1.25 Cm",
  "D7465 Destruction Of Lesion(S) By Physical Or Chemical Method, By Report",
  "D7471 Removal Of Lateral Exostosis (Maxilla Or Mandible)",
  "D7472 Removal Of Torus Palatinus",
  "D7473 Removal Of Torus Mandibularis",
  "D7485 Reduction Of Osseous Tuberosity",
  "D7490 Radical Resection Of Maxilla Or Mandible",
  "D7510 Incision And Drainage Of Abscess - Intraoral Soft Tissue",
  "D7511 Incision And Drainage Of Abscess - Intraoral Soft Tissue - Complicated (Includes Drainage Of Multiple Fascial Spaces)",
  "D7520 Incision And Drainage Of Abscess - Extraoral Soft Tissue",
  "D7521 Incision And Drainage Of Abscess - Extraoral Soft Tissue - Complicated (Includes Drainage Of Multiple Fascial Spaces)",
  "D7530 Removal Of Foreign Body From Mucosa, Skin, Or Subcutaneous Alveolar Tissue",
  "D7540 Removal Of Reaction Producing Foreign Bodies, Musculoskeletal System",
  "D7550 Partial Ostectomy/Sequestrectomy For Removal Of Non-Vital Bone",
  "D7560 Maxillary Sinusotomy For Removal Of Tooth Fragment Or Foreign Body",
  "D7610 Maxilla - Open Reduction (Teeth Immobilized, If Present)",
  "D7620 Maxilla - Closed Reduction (Teeth Immobilized, If Present)",
  "D7630 Mandible - Open Reduction (Teeth Immobilized, If Present)",
  "D7640 Mandible - Closed Reduction (Teeth Immobilized, If Present)",
  "D7650 Malar And/Or Zygomatic Arch - Open Reduction",
  "D7660 Malar And/Or Zygomatic Arch - Closed Reduction",
  "D7670 Alveolus - Closed Reduction, May Include Stabilization Of Teeth",
  "D7671 Alveolus - Open Reduction, May Include Stabilization Of Teeth",
  "D7680 Facial Bones - Complicated Reduction With Fixation And Multiple Surgical Approaches",
  "D7710 Maxilla - Open Reduction",
  "D7720 Maxilla - Closed Reduction",
  "D7730 Mandible - Open Reduction",
  "D7740 Mandible - Closed Reduction",
  "D7750 Malar And/Or Zygomatic Arch - Open Reduction",
  "D7760 Malar And/Or Zygomatic Arch - Closed Reduction",
  "D7770 Alveolus - Open Reduction Stabilization Of Teeth",
  "D7771 Alveolus, Closed Reduction Stabilization Of Teeth",
  "D7780 Facial Bones - Complicated Reduction With Fixation And Multiple Approaches",
  "D7810 Open Reduction Of Dislocation",
  "D7820 Closed Reduction Of Dislocation",
  "D7830 Manipulation Under Anesthesia",
  "D7840 Condylectomy",
  "D7850 Surgical Discectomy, With/Without Implant",
  "D7852 Disc Repair",
  "D7854 Synovectomy",
  "D7856 Myotomy",
  "D7858 Joint Reconstruction",
  "D7860 Arthrotomy",
  "D7865 Arthroplasty",
  "D7870 Arthrocentesis",
  "D7871 Non-Arthroscopic Lysis And Lavage",
  "D7872 Arthroscopy - Diagnosis, With Or Without Biopsy",
  "D7873 Arthroscopy: Lavage And Lysis Of Adhesions",
  "D7874 Arthroscopy: Disc Repositioning And Stabilization",
  "D7875 Arthroscopy: Synovectomy",
  "D7876 Arthroscopy: Discectomy",
  "D7877 Arthroscopy: Debridement",
  "D7880 Occlusal Orthotic Device, By Report",
  "D7881 Occlusal Orthotic Device Adjustment",
  "D7899 Unspecified Tmd Therapy, By Report",
  "D7910 Suture Of Recent Small Wounds Up To 5 Cm",
  "D7911 Complicated Suture - Up To 5 Cm",
  "D7912 Complicated Suture - Greater Than 5 Cm",
  "D7920 Skin Graft (Identify Defect Covered, Location And Type Of Graft)",
  "D7921 Collection And Application Of Autologous Blood Concentrate Product",
  "D7922 Placement Of Intra-Socket Biological Dressing To Aid In Hemostasis Or Clot Stabilization, Per Site",
  "D7940 Osteoplasty - For Orthognathic Deformities",
  "D7941 Osteotomy - Mandibular Rami",
  "D7943 Osteotomy - Mandibular Rami With Bone Graft; Includes Obtaining The Graft",
  "D7944 Osteotomy - Segmented Or Subapical",
  "D7945 Osteotomy - Body Of Mandible",
  "D7946 Lefort I (Maxilla - Total)",
  "D7947 Lefort I (Maxilla - Segmented)",
  "D7948 Lefort Ii Or Lefort Iii (Osteoplasty Of Facial Bones For Midface Hypoplasia Or Retrusion) - Without Bone Graft",
  "D7949 Lefort Ii Or Lefort Iii - With Bone Graft",
  "D7950 Osseous, Osteoperiosteal, Or Cartilage Graft Of The Mandible Or Maxilla - Autogenous Or Nonautogenous, By Report",
  "D7951 Sinus Augmentation With Bone Or Bone Substitutes Via A Lateral Open Approach",
  "D7952 Sinus Augmentation Via A Vertical Approach",
  "D7953 Bone Replacement Graft For Ridge Preservation - Per Site",
  "D7955 Repair Of Maxillofacial Soft And/Or Hard Tissue Defect",
  "D7960 Frenulectomy - Also Known As Frenectomy Or Frenotomy - Separate Procedure Not Incidental To Another Procedure",
  "D7961 Buccal / Labial Frenectomy (Frenulectomy)",
  "D7962 Lingual Frenectomy (Frenulectomy)",
  "D7963 Frenuloplasty",
  "D7970 Excision Of Hyperplastic Tissue - Per Arch",
  "D7971 Excision Of Pericoronal Gingiva",
  "D7972 Surgical Reduction Of Fibrous Tuberosity",
  "D7979 Non – Surgical Sialolithotomy",
  "D7980 Surgical Sialolithotomy",
  "D7981 Excision Of Salivary Gland, By Report",
  "D7982 Sialodochoplasty",
  "D7983 Closure Of Salivary Fistula",
  "D7990 Emergency Tracheotomy",
  "D7991 Coronoidectomy",
  "D7993 Surgical Placement Of Craniofacial Implant – Extra Oral",
  "D7994 Surgical Placement: Zygomatic Implant",
  "D7995 Synthetic Graft - Mandible Or Facial Bones, By Report",
  "D7996 Implant-Mandible For Augmentation Purposes (Excluding Alveolar Ridge), By Report",
  "D7997 Appliance Removal (Not By Dentist Who Placed Appliance), Includes Removal Of Archbar",
  "D7998 Intraoral Placement Of A Fixation Device Not In Conjunction With A Fracture",
  "D7999 Unspecified Oral Surgery Procedure, By Report",
  "D8010 Limited Orthodontic Treatment Of The Primary Dentition",
  "D8020 Limited Orthodontic Treatment Of The Transitional Dentition",
  "D8030 Limited Orthodontic Treatment Of The Adolescent Dentition",
  "D8040 Limited Orthodontic Treatment Of The Adult Dentition",
  "D8050 Interceptive Orthodontic Treatment Of The Primary Dentition",
  "D8060 Interceptive Orthodontic Treatment Of The Transitional Dentition",
  "D8070 Comprehensive Orthodontic Treatment Of The Transitional Dentition",
  "D8080 Comprehensive Orthodontic Treatment Of The Adolescent Dentition",
  "D8090 Comprehensive Orthodontic Treatment Of The Adult Dentition",
  "D8210 Removable Appliance Therapy",
  "D8220 Fixed Appliance Therapy",
  "D8660 Pre-Orthodontic Treatment Examination To Monitor Growth And Development",
  "D8670 Periodic Orthodontic Treatment Visit",
  "D8680 Orthodontic Retention (Removal Of Appliances, Construction And Placement Of Retainer(S))",
  "D8681 Removable Orthodontic Retainer Adjustment",
  "D8690 Orthodontic Treatment (Alternative Billing To A Contract Fee)",
  "D8695 Removal Of Fixed Orthodontic Appliances For Reasons Other Than Completion Of Treatment",
  "D8696 Repair Of Orthodontic Appliance – Maxillary",
  "D8697 Repair Of Orthodontic Appliance – Mandibular",
  "D8698 Re-Cement Or Re-Bond Fixed Retainer – Maxillary",
  "D8699 Re-Cement Or Re-Bond Fixed Retainer – Mandibular",
  "D8701 Repair Of Fixed Retainer, Includes Reattachment – Maxillary",
  "D8702 Repair Of Fixed Retainer, Includes Reattachment – Mandibular",
  "D8703 Replacement Of Lost Or Broken Retainer – Maxillary",
  "D8704 Replacement Of Lost Or Broken Retainer – Mandibular",
  "D8999 Unspecified Orthodontic Procedure, By Report",
  "D9110 Palliative (Emergency) Treatment Of Dental Pain - Minor Procedure",
  "D9120 Fixed Partial Denture Sectioning",
  "D9130 Temporomandibular Joint Dysfunction – Non-Invasive Physical Therapies",
  "D9210 Local Anesthesia Not In Conjunction With Operative Or Surgical Procedures",
  "D9211 Regional Block Anesthesia",
  "D9212 Trigeminal Division Block Anesthesia",
  "D9215 Local Anesthesia In Conjunction With Operative Or Surgical Procedures",
  "D9219 Evaluation For Moderate Sedation, Deep Sedation Or General Anesthesia",
  "D9222 Deep Sedation/General Anesthesia – First 15 Minutes",
  "D9223 Deep Sedation/General Anesthesia – Each Subsequent 15 Minute Increment",
  "D9230 Inhalation Of Nitrous Oxide/Analgesia, Anxiolysis",
  "D9239 Intravenous Moderate  (Conscious) Sedation/Analgesia- First 15 Minutes",
  "D9243 Intravenous Moderate (Conscious) Sedation/Analgesia – Each Subsequent 15 Minute Increment",
  "D9248 Non-Intravenous Conscious Sedation",
  "D9310 Consultation - Diagnostic Service Provided By Dentist Or Physician Other Than Requesting Dentist Or Physician",
  "D9311 Consultation With A Medical Health Care Professional",
  "D9410 House/Extended Care Facility Call",
  "D9420 Hospital Or Ambulatory Surgical Center Call",
  "D9430 Office Visit For Observation (During Regularly Scheduled Hours) - No Other Services Performed",
  "D9440 Office Visit - After Regularly Scheduled Hours",
  "D9450 Case Presentation, Detailed And Extensive Treatment Planning",
  "D9610 Therapeutic Parenteral Drug, Single Administration",
  "D9612 Therapeutic Parenteral Drugs, Two Or More Administrations, Different Medications",
  "D9613 Infiltration Of Sustained Release Therapeutic Drug – Single Or Multiple Sites",
  "D9630 Drugs Or Medicaments Dispensed In The Office For Home Use",
  "D9910 Application Of Desensitizing Medicament",
  "D9911 Application Of Desensitizing Resin For Cervical And/Or Root Surface, Per Tooth",
  "D9920 Behavior Management, By Report",
  "D9930 Treatment Of Complications (Post-Surgical) - Unusual Circumstances, By Report",
  "D9932 Cleaning And Inspection Of Removable Complete Denture, Maxillary",
  "D9933 Cleaning And Inspection Of Removable Complete Denture, Mandibular",
  "D9934 Cleaning And Inspection Of Removable Partial Denture, Maxillary",
  "D9935 Cleaning And Inspection Of Removable Partial Denture, Mandibular",
  "D9941 Fabrication Of Athletic Mouthguard",
  "D9942 Repair And/Or Reline Of Occlusal Guard",
  "D9943 Occlusal Guard Adjustment",
  "D9944 Occlusal Guard – Hard Appliance, Full Arch",
  "D9945 Occlusal Guard – Soft Appliance, Full Arch",
  "D9946 Occlusal Guard – Hard Appliance, Partial Arch",
  "D9950 Occlusion Analysis - Mounted Case",
  "D9951 Occlusal Adjustment - Limited",
  "D9952 Occlusal Adjustment - Complete",
  "D9961 Duplicate/Copy Patient'S Records",
  "D9970 Enamel Microabrasion",
  "D9971 Odontoplasty - Per Tooth",
  "D9972 External Bleaching - Per Arch - Performed In Office",
  "D9973 External Bleaching - Per Tooth",
  "D9974 Internal Bleaching - Per Tooth",
  "D9975 External Bleaching For Home Application, Per Arch; Includes Materials And Fabrication Of Custom Trays",
  "D9985 Sales Tax",
  "D9986 Missed Appointment",
  "D9987 Cancelled Appointment",
  "D9990 Certified Translation Or Sign-Language Services – Per Visit",
  "D9991 Dental Case Management - Addressing Appointment Compliance Barriers",
  "D9992 Dental Case Management - Care Coordination",
  "D9993 Dental Case Management - Motivational Interviewing",
  "D9994 Dental Case Management - Patient Education To Improve Oral Health Literacy",
  "D9995 Teledentistry – Synchronous; Real-Time Encounter",
  "D9996 Teledentistry – Asynchronous; Information Stored And Forwarded To Dentist For Subsequent Review",
  "D9997 Dental Case Management - Patients With Special Health Care Needs",
  "D9999 Unspecified Adjunctive Procedure, By Report",
];

export const Intent = [
  "Ada Guidelines",
  "Affordable Dental Implants",
  "Ai Dentistry Tools",
  "Best Dental Marketing",
  "Buy Dental Equipment",
  "Cloud-Based Dental Software",
  "Continuing Education Dentistry",
  "Dental Chair Sale",
  "Dental Conference Registration",
  "Dental Hygiene Best Practices",
  "Dental Imaging Equipment",
  "Dental Implant Suppliers",
  "Dental Leasing Equipment",
  "Dental Marketing Ideas",
  "Dental Overhead Reduction",
  "Dental Patient Retention",
  "Dental Practice Management",
  "Dental Practice Software",
  "Dental Seo Strategies",
  "Dental Software Comparison",
  "Dental Software Login",
  "Dental Software Pricing",
  "Dental Supplies Discounts",
  "Dental Technology Trends",
  "Dental Webinar Sign-Up",
  "Digital Dental X-Rays",
  "Infection Control Dentistry",
  "Patterson Dental Support",
];


export const USState = 
  [
    { value: 'AK', label: 'Alaska' },
    { value: 'AL', label: 'Alabama' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DC', label: 'Districtof Columbia' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'IA', label: 'Iowa' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MD', label: 'Maryland' },
    { value: 'ME', label: 'Maine' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MT', label: 'Montana' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NY', label: 'NewYork' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VA', label: 'Virginia' },
    { value: 'VT', label: 'Vermont' },
    { value: 'WA', label: 'Washington' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WY', label: 'Wyoming' }
]

export const getStateAndCityPicklist = [
  {
    "AL": [
      "Alexander City",
      "Andalusia",
      "Anniston",
      "Athens",
      "Atmore",
      "Auburn",
      "Bessemer",
      "Birmingham",
      "Chickasaw",
      "Clanton",
      "Cullman",
      "Decatur",
      "Demopolis",
      "Dothan",
      "Enterprise",
      "Eufaula",
      "Florence",
      "Fort Payne",
      "Gadsden",
      "Greenville",
      "Guntersville",
      "Huntsville",
      "Jasper",
      "Marion",
      "Mobile",
      "Montgomery",
      "Opelika",
      "Ozark",
      "Phenix City",
      "Prichard",
      "Scottsboro",
      "Selma",
      "Sheffield",
      "Sylacauga",
      "Talladega",
      "Troy",
      "Tuscaloosa",
      "Tuscumbia",
      "Tuskegee"
    ],
    "AK": [
      "Anchorage",
      "Cordova",
      "Fairbanks",
      "Haines",
      "Homer",
      "Juneau",
      "Ketchikan",
      "Kodiak",
      "Kotzebue",
      "Nome",
      "Palmer",
      "Seward",
      "Sitka",
      "Skagway",
      "Valdez"
    ],
    "AZ": [
      "Ajo",
      "Avondale",
      "Bisbee",
      "Casa Grande",
      "Chandler",
      "Clifton",
      "Douglas",
      "Flagstaff",
      "Florence",
      "Gila Bend",
      "Glendale",
      "Globe",
      "Kingman",
      "Lake Havasu City",
      "Mesa",
      "Nogales",
      "Oraibi",
      "Phoenix",
      "Prescott",
      "Scottsdale",
      "Sierra Vista",
      "Tempe",
      "Tombstone",
      "Tucson",
      "Walpi",
      "Window Rock",
      "Winslow",
      "Yuma"
    ],
    "AR": [
      "Arkadelphia",
      "Arkansas Post",
      "Batesville",
      "Benton",
      "Blytheville",
      "Camden",
      "Conway",
      "Crossett",
      "El Dorado",
      "Fayetteville",
      "Forrest City",
      "Fort Smith",
      "Harrison",
      "Helena",
      "Hope",
      "Hot Springs",
      "Jacksonville",
      "Jonesboro",
      "Little Rock",
      "Magnolia",
      "Morrilton",
      "Newport",
      "North Little Rock",
      "Osceola",
      "Pine Bluff",
      "Rogers",
      "Searcy",
      "Stuttgart",
      "Van Buren",
      "West Memphis"
    ],
    "CA": [
      "Alameda",
      "Alhambra",
      "Anaheim",
      "Antioch",
      "Arcadia",
      "Bakersfield",
      "Barstow",
      "Belmont",
      "Berkeley",
      "Beverly Hills",
      "Brea",
      "Buena Park",
      "Burbank",
      "Calexico",
      "Calistoga",
      "Carlsbad",
      "Carmel",
      "Chico",
      "Chula Vista",
      "Claremont",
      "Compton",
      "Concord",
      "Corona",
      "Coronado",
      "Costa Mesa",
      "Culver City",
      "Daly City",
      "Davis",
      "Downey",
      "El Centro",
      "El Cerrito",
      "El Monte",
      "Escondido",
      "Eureka",
      "Fairfield",
      "Fontana",
      "Fremont",
      "Fresno",
      "Fullerton",
      "Garden Grove",
      "Glendale",
      "Hayward",
      "Hollywood",
      "Huntington Beach",
      "Indio",
      "Inglewood",
      "Irvine",
      "La Habra",
      "Laguna Beach",
      "Lancaster",
      "Livermore",
      "Lodi",
      "Lompoc",
      "Long Beach",
      "Los Angeles",
      "Malibu",
      "Martinez",
      "Marysville",
      "Menlo Park",
      "Merced",
      "Modesto",
      "Monterey",
      "Mountain View",
      "Napa",
      "Needles",
      "Newport Beach",
      "Norwalk",
      "Novato",
      "Oakland",
      "Oceanside",
      "Ojai",
      "Ontario",
      "Orange",
      "Oroville",
      "Oxnard",
      "Pacific Grove",
      "Palm Springs",
      "Palmdale",
      "Palo Alto",
      "Pasadena",
      "Petaluma",
      "Pomona",
      "Port Hueneme",
      "Rancho Cucamonga",
      "Red Bluff",
      "Redding",
      "Redlands",
      "Redondo Beach",
      "Redwood City",
      "Richmond",
      "Riverside",
      "Roseville",
      "Sacramento",
      "Salinas",
      "San Bernardino",
      "San Clemente",
      "San Diego",
      "San Fernando",
      "San Francisco",
      "San Gabriel",
      "San Jose",
      "San Juan Capistrano",
      "San Leandro",
      "San Luis Obispo",
      "San Marino",
      "San Mateo",
      "San Pedro",
      "San Rafael",
      "San Simeon",
      "Santa Ana",
      "Santa Barbara",
      "Santa Clara",
      "Santa Clarita",
      "Santa Cruz",
      "Santa Monica",
      "Santa Rosa",
      "Sausalito",
      "Simi Valley",
      "Sonoma",
      "South San Francisco",
      "Stockton",
      "Sunnyvale",
      "Susanville",
      "Thousand Oaks",
      "Torrance",
      "Turlock",
      "Ukiah",
      "Vallejo",
      "Ventura",
      "Victorville",
      "Visalia",
      "Walnut Creek",
      "Watts",
      "West Covina",
      "Whittier",
      "Woodland",
      "Yorba Linda",
      "Yuba City"
    ],
    "CO": [
      "Alamosa",
      "Aspen",
      "Aurora",
      "Boulder",
      "Breckenridge",
      "Brighton",
      "Canon City",
      "Central City",
      "Climax",
      "Colorado Springs",
      "Cortez",
      "Cripple Creek",
      "Denver",
      "Durango",
      "Englewood",
      "Estes Park",
      "Fort Collins",
      "Fort Morgan",
      "Georgetown",
      "Glenwood Springs",
      "Golden",
      "Grand Junction",
      "Greeley",
      "Gunnison",
      "La Junta",
      "Leadville",
      "Littleton",
      "Longmont",
      "Loveland",
      "Montrose",
      "Ouray",
      "Pagosa Springs",
      "Pueblo",
      "Silverton",
      "Steamboat Springs",
      "Sterling",
      "Telluride",
      "Trinidad",
      "Vail",
      "Walsenburg",
      "Westminster"
    ],
    "CT": [
      "Ansonia",
      "Berlin",
      "Bloomfield",
      "Branford",
      "Bridgeport",
      "Bristol",
      "Coventry",
      "Danbury",
      "Darien",
      "Derby",
      "East Hartford",
      "East Haven",
      "Enfield",
      "Fairfield",
      "Farmington",
      "Greenwich",
      "Groton",
      "Guilford",
      "Hamden",
      "Hartford",
      "Lebanon",
      "Litchfield",
      "Manchester",
      "Mansfield",
      "Meriden",
      "Middletown",
      "Milford",
      "Mystic",
      "Naugatuck",
      "New Britain",
      "New Haven",
      "New London",
      "North Haven",
      "Norwalk",
      "Norwich",
      "Old Saybrook",
      "Orange",
      "Seymour",
      "Shelton",
      "Simsbury",
      "Southington",
      "Stamford",
      "Stonington",
      "Stratford",
      "Torrington",
      "Wallingford",
      "Waterbury",
      "Waterford",
      "Watertown",
      "West Hartford",
      "West Haven",
      "Westport",
      "Wethersfield",
      "Willimantic",
      "Windham",
      "Windsor",
      "Windsor Locks",
      "Winsted"
    ],
    "DE": [
      "Dover",
      "Lewes",
      "Milford",
      "New Castle",
      "Newark",
      "Smyrna",
      "Wilmington"
    ],
    "FL": [
      "Apalachicola",
      "Bartow",
      "Belle Glade",
      "Boca Raton",
      "Bradenton",
      "Cape Coral",
      "Clearwater",
      "Cocoa Beach",
      "Cocoa-Rockledge",
      "Coral Gables",
      "Daytona Beach",
      "De Land",
      "Deerfield Beach",
      "Delray Beach",
      "Fernandina Beach",
      "Fort Lauderdale",
      "Fort Myers",
      "Fort Pierce",
      "Fort Walton Beach",
      "Gainesville",
      "Hallandale Beach",
      "Hialeah",
      "Hollywood",
      "Homestead",
      "Jacksonville",
      "Key West",
      "Lake City",
      "Lake Wales",
      "Lakeland",
      "Largo",
      "Melbourne",
      "Miami",
      "Miami Beach",
      "Naples",
      "New Smyrna Beach",
      "Ocala",
      "Orlando",
      "Ormond Beach",
      "Palatka",
      "Palm Bay",
      "Palm Beach",
      "Panama City",
      "Pensacola",
      "Pompano Beach",
      "Saint Augustine",
      "Saint Petersburg",
      "Sanford",
      "Sarasota",
      "Sebring",
      "Tallahassee",
      "Tampa",
      "Tarpon Springs",
      "Titusville",
      "Venice",
      "West Palm Beach",
      "White Springs",
      "Winter Haven",
      "Winter Park"
    ],
    "GA": [
      "Albany",
      "Americus",
      "Andersonville",
      "Athens",
      "Atlanta",
      "Augusta",
      "Bainbridge",
      "Blairsville",
      "Brunswick",
      "Calhoun",
      "Carrollton",
      "Columbus",
      "Dahlonega",
      "Dalton",
      "Darien",
      "Decatur",
      "Douglas",
      "East Point",
      "Fitzgerald",
      "Fort Valley",
      "Gainesville",
      "La Grange",
      "Macon",
      "Marietta",
      "Milledgeville",
      "Plains",
      "Rome",
      "Savannah",
      "Toccoa",
      "Valdosta",
      "Warm Springs",
      "Warner Robins",
      "Washington",
      "Waycross"
    ],
    "HI": [
      "Hanalei",
      "Hilo",
      "Honaunau",
      "Honolulu",
      "Kahului",
      "Kaneohe",
      "Kapaa",
      "Kawaihae",
      "Lahaina",
      "Laie",
      "Wahiawa",
      "Wailuku",
      "Waimea"
    ],
    "ID": [
      "Blackfoot",
      "Boise",
      "Bonners Ferry",
      "Caldwell",
      "Coeur d’Alene",
      "Idaho City",
      "Idaho Falls",
      "Kellogg",
      "Lewiston",
      "Moscow",
      "Nampa",
      "Pocatello",
      "Priest River",
      "Rexburg",
      "Sun Valley",
      "Twin Falls"
    ],
    "IL": [
      "Alton",
      "Arlington Heights",
      "Arthur",
      "Aurora",
      "Belleville",
      "Belvidere",
      "Bloomington",
      "Brookfield",
      "Cahokia",
      "Cairo",
      "Calumet City",
      "Canton",
      "Carbondale",
      "Carlinville",
      "Carthage",
      "Centralia",
      "Champaign",
      "Charleston",
      "Chester",
      "Chicago",
      "Chicago Heights",
      "Cicero",
      "Collinsville",
      "Danville",
      "Decatur",
      "DeKalb",
      "Des Plaines",
      "Dixon",
      "East Moline",
      "East Saint Louis",
      "Effingham",
      "Elgin",
      "Elmhurst",
      "Evanston",
      "Freeport",
      "Galena",
      "Galesburg",
      "Glen Ellyn",
      "Glenview",
      "Granite City",
      "Harrisburg",
      "Herrin",
      "Highland Park",
      "Jacksonville",
      "Joliet",
      "Kankakee",
      "Kaskaskia",
      "Kewanee",
      "La Salle",
      "Lake Forest",
      "Libertyville",
      "Lincoln",
      "Lisle",
      "Lombard",
      "Macomb",
      "Mattoon",
      "Moline",
      "Monmouth",
      "Mount Vernon",
      "Mundelein",
      "Naperville",
      "Nauvoo",
      "Normal",
      "North Chicago",
      "Oak Park",
      "Oregon",
      "Ottawa",
      "Palatine",
      "Park Forest",
      "Park Ridge",
      "Pekin",
      "Peoria",
      "Petersburg",
      "Pontiac",
      "Quincy",
      "Rantoul",
      "River Forest",
      "Rock Island",
      "Rockford",
      "Salem",
      "Shawneetown",
      "Skokie",
      "South Holland",
      "Springfield",
      "Streator",
      "Summit",
      "Urbana",
      "Vandalia",
      "Virden",
      "Waukegan",
      "Wheaton",
      "Wilmette",
      "Winnetka",
      "Wood River",
      "Zion"
    ],
    "IN": [
      "Anderson",
      "Bedford",
      "Bloomington",
      "Columbus",
      "Connersville",
      "Corydon",
      "Crawfordsville",
      "East Chicago",
      "Elkhart",
      "Elwood",
      "Evansville",
      "Fort Wayne",
      "French Lick",
      "Gary",
      "Geneva",
      "Goshen",
      "Greenfield",
      "Hammond",
      "Hobart",
      "Huntington",
      "Indianapolis",
      "Jeffersonville",
      "Kokomo",
      "Lafayette",
      "Madison",
      "Marion",
      "Michigan City",
      "Mishawaka",
      "Muncie",
      "Nappanee",
      "Nashville",
      "New Albany",
      "New Castle",
      "New Harmony",
      "Peru",
      "Plymouth",
      "Richmond",
      "Santa Claus",
      "Shelbyville",
      "South Bend",
      "Terre Haute",
      "Valparaiso",
      "Vincennes",
      "Wabash",
      "West Lafayette"
    ],
    "IA": [
      "Amana Colonies",
      "Ames",
      "Boone",
      "Burlington",
      "Cedar Falls",
      "Cedar Rapids",
      "Charles City",
      "Cherokee",
      "Clinton",
      "Council Bluffs",
      "Davenport",
      "Des Moines",
      "Dubuque",
      "Estherville",
      "Fairfield",
      "Fort Dodge",
      "Grinnell",
      "Indianola",
      "Iowa City",
      "Keokuk",
      "Mason City",
      "Mount Pleasant",
      "Muscatine",
      "Newton",
      "Oskaloosa",
      "Ottumwa",
      "Sioux City",
      "Waterloo",
      "Webster City",
      "West Des Moines"
    ],
    "KS": [
      "Abilene",
      "Arkansas City",
      "Atchison",
      "Chanute",
      "Coffeyville",
      "Council Grove",
      "Dodge City",
      "Emporia",
      "Fort Scott",
      "Garden City",
      "Great Bend",
      "Hays",
      "Hutchinson",
      "Independence",
      "Junction City",
      "Kansas City",
      "Lawrence",
      "Leavenworth",
      "Liberal",
      "Manhattan",
      "McPherson",
      "Medicine Lodge",
      "Newton",
      "Olathe",
      "Osawatomie",
      "Ottawa",
      "Overland Park",
      "Pittsburg",
      "Salina",
      "Shawnee",
      "Smith Center",
      "Topeka",
      "Wichita"
    ],
    "KY": [
      "Ashland",
      "Barbourville",
      "Bardstown",
      "Berea",
      "Boonesborough",
      "Bowling Green",
      "Campbellsville",
      "Covington",
      "Danville",
      "Elizabethtown",
      "Frankfort",
      "Harlan",
      "Harrodsburg",
      "Hazard",
      "Henderson",
      "Hodgenville",
      "Hopkinsville",
      "Lexington",
      "Louisville",
      "Mayfield",
      "Maysville",
      "Middlesboro",
      "Newport",
      "Owensboro",
      "Paducah",
      "Paris",
      "Richmond"
    ],
    "LA": [
      "Abbeville",
      "Alexandria",
      "Bastrop",
      "Baton Rouge",
      "Bogalusa",
      "Bossier City",
      "Gretna",
      "Houma",
      "Lafayette",
      "Lake Charles",
      "Monroe",
      "Morgan City",
      "Natchitoches",
      "New Iberia",
      "New Orleans",
      "Opelousas",
      "Ruston",
      "Saint Martinville",
      "Shreveport",
      "Thibodaux"
    ],
    "ME": [
      "Auburn",
      "Augusta",
      "Bangor",
      "Bar Harbor",
      "Bath",
      "Belfast",
      "Biddeford",
      "Boothbay Harbor",
      "Brunswick",
      "Calais",
      "Caribou",
      "Castine",
      "Eastport",
      "Ellsworth",
      "Farmington",
      "Fort Kent",
      "Gardiner",
      "Houlton",
      "Kennebunkport",
      "Kittery",
      "Lewiston",
      "Lubec",
      "Machias",
      "Orono",
      "Portland",
      "Presque Isle",
      "Rockland",
      "Rumford",
      "Saco",
      "Scarborough",
      "Waterville",
      "York"
    ],
    "MD": [
      "Aberdeen",
      "Annapolis",
      "Baltimore",
      "Bethesda-Chevy Chase",
      "Bowie",
      "Cambridge",
      "Catonsville",
      "College Park",
      "Columbia",
      "Cumberland",
      "Easton",
      "Elkton",
      "Emmitsburg",
      "Frederick",
      "Greenbelt",
      "Hagerstown",
      "Hyattsville",
      "Laurel",
      "Oakland",
      "Ocean City",
      "Rockville",
      "Saint Marys City",
      "Salisbury",
      "Silver Spring",
      "Takoma Park",
      "Towson",
      "Westminster"
    ],
    "MA": [
      "Abington",
      "Adams",
      "Amesbury",
      "Amherst",
      "Andover",
      "Arlington",
      "Athol",
      "Attleboro",
      "Barnstable",
      "Bedford",
      "Beverly",
      "Boston",
      "Bourne",
      "Braintree",
      "Brockton",
      "Brookline",
      "Cambridge",
      "Canton",
      "Charlestown",
      "Chelmsford",
      "Chelsea",
      "Chicopee",
      "Clinton",
      "Cohasset",
      "Concord",
      "Danvers",
      "Dartmouth",
      "Dedham",
      "Dennis",
      "Duxbury",
      "Eastham",
      "Edgartown",
      "Everett",
      "Fairhaven",
      "Fall River",
      "Falmouth",
      "Fitchburg",
      "Framingham",
      "Gloucester",
      "Great Barrington",
      "Greenfield",
      "Groton",
      "Harwich",
      "Haverhill",
      "Hingham",
      "Holyoke",
      "Hyannis",
      "Ipswich",
      "Lawrence",
      "Lenox",
      "Leominster",
      "Lexington",
      "Lowell",
      "Ludlow",
      "Lynn",
      "Malden",
      "Marblehead",
      "Marlborough",
      "Medford",
      "Milton",
      "Nahant",
      "Natick",
      "New Bedford",
      "Newburyport",
      "Newton",
      "North Adams",
      "Northampton",
      "Norton",
      "Norwood",
      "Peabody",
      "Pittsfield",
      "Plymouth",
      "Provincetown",
      "Quincy",
      "Randolph",
      "Revere",
      "Salem",
      "Sandwich",
      "Saugus",
      "Somerville",
      "South Hadley",
      "Springfield",
      "Stockbridge",
      "Stoughton",
      "Sturbridge",
      "Sudbury",
      "Taunton",
      "Tewksbury",
      "Truro",
      "Watertown",
      "Webster",
      "Wellesley",
      "Wellfleet",
      "West Bridgewater",
      "West Springfield",
      "Westfield",
      "Weymouth",
      "Whitman",
      "Williamstown",
      "Woburn",
      "Woods Hole",
      "Worcester"
    ],
    "MI": [
      "Adrian",
      "Alma",
      "Ann Arbor",
      "Battle Creek",
      "Bay City",
      "Benton Harbor",
      "Bloomfield Hills",
      "Cadillac",
      "Charlevoix",
      "Cheboygan",
      "Dearborn",
      "Detroit",
      "East Lansing",
      "Eastpointe",
      "Ecorse",
      "Escanaba",
      "Flint",
      "Grand Haven",
      "Grand Rapids",
      "Grayling",
      "Grosse Pointe",
      "Hancock",
      "Highland Park",
      "Holland",
      "Houghton",
      "Interlochen",
      "Iron Mountain",
      "Ironwood",
      "Ishpeming",
      "Jackson",
      "Kalamazoo",
      "Lansing",
      "Livonia",
      "Ludington",
      "Mackinaw City",
      "Manistee",
      "Marquette",
      "Menominee",
      "Midland",
      "Monroe",
      "Mount Clemens",
      "Mount Pleasant",
      "Muskegon",
      "Niles",
      "Petoskey",
      "Pontiac",
      "Port Huron",
      "Royal Oak",
      "Saginaw",
      "Saint Ignace",
      "Saint Joseph",
      "Sault Sainte Marie",
      "Traverse City",
      "Trenton",
      "Warren",
      "Wyandotte",
      "Ypsilanti"
    ],
    "MN": [
      "Albert Lea",
      "Alexandria",
      "Austin",
      "Bemidji",
      "Bloomington",
      "Brainerd",
      "Crookston",
      "Duluth",
      "Ely",
      "Eveleth",
      "Faribault",
      "Fergus Falls",
      "Hastings",
      "Hibbing",
      "International Falls",
      "Little Falls",
      "Mankato",
      "Minneapolis",
      "Moorhead",
      "New Ulm",
      "Northfield",
      "Owatonna",
      "Pipestone",
      "Red Wing",
      "Rochester",
      "Saint Cloud",
      "Saint Paul",
      "Sauk Centre",
      "South Saint Paul",
      "Stillwater",
      "Virginia",
      "Willmar",
      "Winona"
    ],
    "MS": [
      "Bay Saint Louis",
      "Biloxi",
      "Canton",
      "Clarksdale",
      "Columbia",
      "Columbus",
      "Corinth",
      "Greenville",
      "Greenwood",
      "Grenada",
      "Gulfport",
      "Hattiesburg",
      "Holly Springs",
      "Jackson",
      "Laurel",
      "Meridian",
      "Natchez",
      "Ocean Springs",
      "Oxford",
      "Pascagoula",
      "Pass Christian",
      "Philadelphia",
      "Port Gibson",
      "Starkville",
      "Tupelo",
      "Vicksburg",
      "West Point",
      "Yazoo City"
    ],
    "MO": [
      "Boonville",
      "Branson",
      "Cape Girardeau",
      "Carthage",
      "Chillicothe",
      "Clayton",
      "Columbia",
      "Excelsior Springs",
      "Ferguson",
      "Florissant",
      "Fulton",
      "Hannibal",
      "Independence",
      "Jefferson City",
      "Joplin",
      "Kansas City",
      "Kirksville",
      "Lamar",
      "Lebanon",
      "Lexington",
      "Maryville",
      "Mexico",
      "Monett",
      "Neosho",
      "New Madrid",
      "Rolla",
      "Saint Charles",
      "Saint Joseph",
      "Saint Louis",
      "Sainte Genevieve",
      "Salem",
      "Sedalia",
      "Springfield",
      "Warrensburg",
      "West Plains"
    ],
    "MT": [
      "Anaconda",
      "Billings",
      "Bozeman",
      "Butte",
      "Dillon",
      "Fort Benton",
      "Glendive",
      "Great Falls",
      "Havre",
      "Helena",
      "Kalispell",
      "Lewistown",
      "Livingston",
      "Miles City",
      "Missoula",
      "Virginia City"
    ],
    "NE": [
      "Beatrice",
      "Bellevue",
      "Boys Town",
      "Chadron",
      "Columbus",
      "Fremont",
      "Grand Island",
      "Hastings",
      "Kearney",
      "Lincoln",
      "McCook",
      "Minden",
      "Nebraska City",
      "Norfolk",
      "North Platte",
      "Omaha",
      "Plattsmouth",
      "Red Cloud",
      "Sidney"
    ],
    "NV": [
      "Boulder City",
      "Carson City",
      "Elko",
      "Ely",
      "Fallon",
      "Genoa",
      "Goldfield",
      "Henderson",
      "Las Vegas",
      "North Las Vegas",
      "Reno",
      "Sparks",
      "Virginia City",
      "Winnemucca"
    ],
    "NH": [
      "Berlin",
      "Claremont",
      "Concord",
      "Derry",
      "Dover",
      "Durham",
      "Exeter",
      "Franklin",
      "Hanover",
      "Hillsborough",
      "Keene",
      "Laconia",
      "Lebanon",
      "Manchester",
      "Nashua",
      "Peterborough",
      "Plymouth",
      "Portsmouth",
      "Rochester",
      "Salem",
      "Somersworth"
    ],
    "NJ": [
      "Asbury Park",
      "Atlantic City",
      "Bayonne",
      "Bloomfield",
      "Bordentown",
      "Bound Brook",
      "Bridgeton",
      "Burlington",
      "Caldwell",
      "Camden",
      "Cape May",
      "Clifton",
      "Cranford",
      "East Orange",
      "Edison",
      "Elizabeth",
      "Englewood",
      "Fort Lee",
      "Glassboro",
      "Hackensack",
      "Haddonfield",
      "Hoboken",
      "Irvington",
      "Jersey City",
      "Lakehurst",
      "Lakewood",
      "Long Beach",
      "Long Branch",
      "Madison",
      "Menlo Park",
      "Millburn",
      "Millville",
      "Montclair",
      "Morristown",
      "Mount Holly",
      "New Brunswick",
      "New Milford",
      "Newark",
      "Ocean City",
      "Orange",
      "Parsippany–Troy Hills",
      "Passaic",
      "Paterson",
      "Perth Amboy",
      "Plainfield",
      "Princeton",
      "Ridgewood",
      "Roselle",
      "Rutherford",
      "Salem",
      "Somerville",
      "South Orange Village",
      "Totowa",
      "Trenton",
      "Union",
      "Union City",
      "Vineland",
      "Wayne",
      "Weehawken",
      "West New York",
      "West Orange",
      "Willingboro",
      "Woodbridge"
    ],
    "NM": [
      "Acoma",
      "Alamogordo",
      "Albuquerque",
      "Artesia",
      "Belen",
      "Carlsbad",
      "Clovis",
      "Deming",
      "Farmington",
      "Gallup",
      "Grants",
      "Hobbs",
      "Las Cruces",
      "Las Vegas",
      "Los Alamos",
      "Lovington",
      "Portales",
      "Raton",
      "Roswell",
      "Santa Fe",
      "Shiprock",
      "Silver City",
      "Socorro",
      "Taos",
      "Truth or Consequences",
      "Tucumcari"
    ],
    "NY": [
      "Albany",
      "Amsterdam",
      "Auburn",
      "Babylon",
      "Batavia",
      "Beacon",
      "Bedford",
      "Binghamton",
      "Bronx",
      "Brooklyn",
      "Buffalo",
      "Chautauqua",
      "Cheektowaga",
      "Clinton",
      "Cohoes",
      "Coney Island",
      "Cooperstown",
      "Corning",
      "Cortland",
      "Crown Point",
      "Dunkirk",
      "East Aurora",
      "East Hampton",
      "Eastchester",
      "Elmira",
      "Flushing",
      "Forest Hills",
      "Fredonia",
      "Garden City",
      "Geneva",
      "Glens Falls",
      "Gloversville",
      "Great Neck",
      "Hammondsport",
      "Harlem",
      "Hempstead",
      "Herkimer",
      "Hudson",
      "Huntington",
      "Hyde Park",
      "Ilion",
      "Ithaca",
      "Jamestown",
      "Johnstown",
      "Kingston",
      "Lackawanna",
      "Lake Placid",
      "Levittown",
      "Lockport",
      "Mamaroneck",
      "Manhattan",
      "Massena",
      "Middletown",
      "Mineola",
      "Mount Vernon",
      "New Paltz",
      "New Rochelle",
      "New Windsor",
      "New York City",
      "Newburgh",
      "Niagara Falls",
      "North Hempstead",
      "Nyack",
      "Ogdensburg",
      "Olean",
      "Oneida",
      "Oneonta",
      "Ossining",
      "Oswego",
      "Oyster Bay",
      "Palmyra",
      "Peekskill",
      "Plattsburgh",
      "Port Washington",
      "Potsdam",
      "Poughkeepsie",
      "Queens",
      "Rensselaer",
      "Rochester",
      "Rome",
      "Rotterdam",
      "Rye",
      "Sag Harbor",
      "Saranac Lake",
      "Saratoga Springs",
      "Scarsdale",
      "Schenectady",
      "Seneca Falls",
      "Southampton",
      "Staten Island",
      "Stony Brook",
      "Stony Point",
      "Syracuse",
      "Tarrytown",
      "Ticonderoga",
      "Tonawanda",
      "Troy",
      "Utica",
      "Watertown",
      "Watervliet",
      "Watkins Glen",
      "West Seneca",
      "White Plains",
      "Woodstock",
      "Yonkers"
    ],
    "NC": [
      "Asheboro",
      "Asheville",
      "Bath",
      "Beaufort",
      "Boone",
      "Burlington",
      "Chapel Hill",
      "Charlotte",
      "Concord",
      "Durham",
      "Edenton",
      "Elizabeth City",
      "Fayetteville",
      "Gastonia",
      "Goldsboro",
      "Greensboro",
      "Greenville",
      "Halifax",
      "Henderson",
      "Hickory",
      "High Point",
      "Hillsborough",
      "Jacksonville",
      "Kinston",
      "Kitty Hawk",
      "Lumberton",
      "Morehead City",
      "Morganton",
      "Nags Head",
      "New Bern",
      "Pinehurst",
      "Raleigh",
      "Rocky Mount",
      "Salisbury",
      "Shelby",
      "Washington",
      "Wilmington",
      "Wilson",
      "Winston-Salem"
    ],
    "ND": [
      "Bismarck",
      "Devils Lake",
      "Dickinson",
      "Fargo",
      "Grand Forks",
      "Jamestown",
      "Mandan",
      "Minot",
      "Rugby",
      "Valley City",
      "Wahpeton",
      "Williston"
    ],
    "OH": [
      "Akron",
      "Alliance",
      "Ashtabula",
      "Athens",
      "Barberton",
      "Bedford",
      "Bellefontaine",
      "Bowling Green",
      "Canton",
      "Chillicothe",
      "Cincinnati",
      "Cleveland",
      "Cleveland Heights",
      "Columbus",
      "Conneaut",
      "Cuyahoga Falls",
      "Dayton",
      "Defiance",
      "Delaware",
      "East Cleveland",
      "East Liverpool",
      "Elyria",
      "Euclid",
      "Findlay",
      "Gallipolis",
      "Greenville",
      "Hamilton",
      "Kent",
      "Kettering",
      "Lakewood",
      "Lancaster",
      "Lima",
      "Lorain",
      "Mansfield",
      "Marietta",
      "Marion",
      "Martins Ferry",
      "Massillon",
      "Mentor",
      "Middletown",
      "Milan",
      "Mount Vernon",
      "New Philadelphia",
      "Newark",
      "Niles",
      "North College Hill",
      "Norwalk",
      "Oberlin",
      "Painesville",
      "Parma",
      "Piqua",
      "Portsmouth",
      "Put-in-Bay",
      "Salem",
      "Sandusky",
      "Shaker Heights",
      "Springfield",
      "Steubenville",
      "Tiffin",
      "Toledo",
      "Urbana",
      "Warren",
      "Wooster",
      "Worthington",
      "Xenia",
      "Yellow Springs",
      "Youngstown",
      "Zanesville"
    ],
    "OK": [
      "Ada",
      "Altus",
      "Alva",
      "Anadarko",
      "Ardmore",
      "Bartlesville",
      "Bethany",
      "Chickasha",
      "Claremore",
      "Clinton",
      "Cushing",
      "Duncan",
      "Durant",
      "Edmond",
      "El Reno",
      "Elk City",
      "Enid",
      "Eufaula",
      "Frederick",
      "Guthrie",
      "Guymon",
      "Hobart",
      "Holdenville",
      "Hugo",
      "Lawton",
      "McAlester",
      "Miami",
      "Midwest City",
      "Moore",
      "Muskogee",
      "Norman",
      "Oklahoma City",
      "Okmulgee",
      "Pauls Valley",
      "Pawhuska",
      "Perry",
      "Ponca City",
      "Pryor",
      "Sallisaw",
      "Sand Springs",
      "Sapulpa",
      "Seminole",
      "Shawnee",
      "Stillwater",
      "Tahlequah",
      "The Village",
      "Tulsa",
      "Vinita",
      "Wewoka",
      "Woodward"
    ],
    "OR": [
      "Albany",
      "Ashland",
      "Astoria",
      "Baker City",
      "Beaverton",
      "Bend",
      "Brookings",
      "Burns",
      "Coos Bay",
      "Corvallis",
      "Eugene",
      "Grants Pass",
      "Hillsboro",
      "Hood River",
      "Jacksonville",
      "John Day",
      "Klamath Falls",
      "La Grande",
      "Lake Oswego",
      "Lakeview",
      "McMinnville",
      "Medford",
      "Newberg",
      "Newport",
      "Ontario",
      "Oregon City",
      "Pendleton",
      "Port Orford",
      "Portland",
      "Prineville",
      "Redmond",
      "Reedsport",
      "Roseburg",
      "Salem",
      "Seaside",
      "Springfield",
      "The Dalles",
      "Tillamook"
    ],
    "PA": [
      "Abington",
      "Aliquippa",
      "Allentown",
      "Altoona",
      "Ambridge",
      "Bedford",
      "Bethlehem",
      "Bloomsburg",
      "Bradford",
      "Bristol",
      "Carbondale",
      "Carlisle",
      "Chambersburg",
      "Chester",
      "Columbia",
      "Easton",
      "Erie",
      "Franklin",
      "Germantown",
      "Gettysburg",
      "Greensburg",
      "Hanover",
      "Harmony",
      "Harrisburg",
      "Hazleton",
      "Hershey",
      "Homestead",
      "Honesdale",
      "Indiana",
      "Jeannette",
      "Jim Thorpe",
      "Johnstown",
      "Lancaster",
      "Lebanon",
      "Levittown",
      "Lewistown",
      "Lock Haven",
      "Lower Southampton",
      "McKeesport",
      "Meadville",
      "Middletown",
      "Monroeville",
      "Nanticoke",
      "New Castle",
      "New Hope",
      "New Kensington",
      "Norristown",
      "Oil City",
      "Philadelphia",
      "Phoenixville",
      "Pittsburgh",
      "Pottstown",
      "Pottsville",
      "Reading",
      "Scranton",
      "Shamokin",
      "Sharon",
      "State College",
      "Stroudsburg",
      "Sunbury",
      "Swarthmore",
      "Tamaqua",
      "Titusville",
      "Uniontown",
      "Warren",
      "Washington",
      "West Chester",
      "Wilkes-Barre",
      "Williamsport",
      "York"
    ],
    "RI": [
      "Barrington",
      "Bristol",
      "Central Falls",
      "Cranston",
      "East Greenwich",
      "East Providence",
      "Kingston",
      "Middletown",
      "Narragansett",
      "Newport",
      "North Kingstown",
      "Pawtucket",
      "Portsmouth",
      "Providence",
      "South Kingstown",
      "Tiverton",
      "Warren",
      "Warwick",
      "Westerly",
      "Wickford",
      "Woonsocket"
    ],
    "SC": [
      "Abbeville",
      "Aiken",
      "Anderson",
      "Beaufort",
      "Camden",
      "Charleston",
      "Columbia",
      "Darlington",
      "Florence",
      "Gaffney",
      "Georgetown",
      "Greenville",
      "Greenwood",
      "Hartsville",
      "Lancaster",
      "Mount Pleasant",
      "Myrtle Beach",
      "Orangeburg",
      "Rock Hill",
      "Spartanburg",
      "Sumter",
      "Union"
    ],
    "SD": [
      "Aberdeen",
      "Belle Fourche",
      "Brookings",
      "Canton",
      "Custer",
      "De Smet",
      "Deadwood",
      "Hot Springs",
      "Huron",
      "Lead",
      "Madison",
      "Milbank",
      "Mitchell",
      "Mobridge",
      "Pierre",
      "Rapid City",
      "Sioux Falls",
      "Spearfish",
      "Sturgis",
      "Vermillion",
      "Watertown",
      "Yankton"
    ],
    "TN": [
      "Alcoa",
      "Athens",
      "Chattanooga",
      "Clarksville",
      "Cleveland",
      "Columbia",
      "Cookeville",
      "Dayton",
      "Elizabethton",
      "Franklin",
      "Gallatin",
      "Gatlinburg",
      "Greeneville",
      "Jackson",
      "Johnson City",
      "Jonesborough",
      "Kingsport",
      "Knoxville",
      "Lebanon",
      "Maryville",
      "Memphis",
      "Morristown",
      "Murfreesboro",
      "Nashville",
      "Norris",
      "Oak Ridge",
      "Shelbyville",
      "Tullahoma"
    ],
    "TX": [
      "Abilene",
      "Alpine",
      "Amarillo",
      "Arlington",
      "Austin",
      "Baytown",
      "Beaumont",
      "Big Spring",
      "Borger",
      "Brownsville",
      "Bryan",
      "Canyon",
      "Cleburne",
      "College Station",
      "Corpus Christi",
      "Crystal City",
      "Dallas",
      "Del Rio",
      "Denison",
      "Denton",
      "Eagle Pass",
      "Edinburg",
      "El Paso",
      "Fort Worth",
      "Freeport",
      "Galveston",
      "Garland",
      "Goliad",
      "Greenville",
      "Harlingen",
      "Houston",
      "Huntsville",
      "Irving",
      "Johnson City",
      "Kilgore",
      "Killeen",
      "Kingsville",
      "Laredo",
      "Longview",
      "Lubbock",
      "Lufkin",
      "Marshall",
      "McAllen",
      "McKinney",
      "Mesquite",
      "Midland",
      "Mission",
      "Nacogdoches",
      "New Braunfels",
      "Odessa",
      "Orange",
      "Pampa",
      "Paris",
      "Pasadena",
      "Pecos",
      "Pharr",
      "Plainview",
      "Plano",
      "Port Arthur",
      "Port Lavaca",
      "Richardson",
      "San Angelo",
      "San Antonio",
      "San Felipe",
      "San Marcos",
      "Sherman",
      "Sweetwater",
      "Temple",
      "Texarkana",
      "Texas City",
      "Tyler",
      "Uvalde",
      "Victoria",
      "Waco",
      "Weatherford",
      "Wichita Falls",
      "Ysleta"
    ],
    "UT": [
      "Alta",
      "American Fork",
      "Bountiful",
      "Brigham City",
      "Cedar City",
      "Clearfield",
      "Delta",
      "Fillmore",
      "Green River",
      "Heber City",
      "Kanab",
      "Layton",
      "Lehi",
      "Logan",
      "Manti",
      "Moab",
      "Monticello",
      "Murray",
      "Nephi",
      "Ogden",
      "Orderville",
      "Orem",
      "Panguitch",
      "Park City",
      "Payson",
      "Price",
      "Provo",
      "Saint George",
      "Salt Lake City",
      "Spanish Fork",
      "Springville",
      "Tooele",
      "Vernal"
    ],
    "VT": [
      "Barre",
      "Bellows Falls",
      "Bennington",
      "Brattleboro",
      "Burlington",
      "Essex",
      "Manchester",
      "Middlebury",
      "Montpelier",
      "Newport",
      "Plymouth",
      "Rutland",
      "Saint Albans",
      "Saint Johnsbury",
      "Sharon",
      "Winooski"
    ],
    "VA": [
      "Abingdon",
      "Alexandria",
      "Bristol",
      "Charlottesville",
      "Chesapeake",
      "Danville",
      "Fairfax",
      "Falls Church",
      "Fredericksburg",
      "Hampton",
      "Hanover",
      "Hopewell",
      "Lexington",
      "Lynchburg",
      "Manassas",
      "Martinsville",
      "New Market",
      "Newport News",
      "Norfolk",
      "Petersburg",
      "Portsmouth",
      "Reston",
      "Richmond",
      "Roanoke",
      "Staunton",
      "Suffolk",
      "Virginia Beach",
      "Waynesboro",
      "Williamsburg",
      "Winchester"
    ],
    "WA": [
      "Aberdeen",
      "Anacortes",
      "Auburn",
      "Bellevue",
      "Bellingham",
      "Bremerton",
      "Centralia",
      "Coulee Dam",
      "Coupeville",
      "Ellensburg",
      "Ephrata",
      "Everett",
      "Hoquiam",
      "Kelso",
      "Kennewick",
      "Longview",
      "Moses Lake",
      "Oak Harbor",
      "Olympia",
      "Pasco",
      "Point Roberts",
      "Port Angeles",
      "Pullman",
      "Puyallup",
      "Redmond",
      "Renton",
      "Richland",
      "Seattle",
      "Spokane",
      "Tacoma",
      "Vancouver",
      "Walla Walla",
      "Wenatchee",
      "Yakima"
    ],
    "WV": [
      "Bath",
      "Beckley",
      "Bluefield",
      "Buckhannon",
      "Charles Town",
      "Charleston",
      "Clarksburg",
      "Elkins",
      "Fairmont",
      "Grafton",
      "Harpers Ferry",
      "Hillsboro",
      "Hinton",
      "Huntington",
      "Keyser",
      "Lewisburg",
      "Logan",
      "Martinsburg",
      "Morgantown",
      "Moundsville",
      "New Martinsville",
      "Parkersburg",
      "Philippi",
      "Point Pleasant",
      "Princeton",
      "Romney",
      "Shepherdstown",
      "South Charleston",
      "Summersville",
      "Weirton",
      "Welch",
      "Wellsburg",
      "Weston",
      "Wheeling",
      "White Sulphur Springs",
      "Williamson"
    ],
    "WI": [
      "Appleton",
      "Ashland",
      "Baraboo",
      "Belmont",
      "Beloit",
      "Eau Claire",
      "Fond du Lac",
      "Green Bay",
      "Hayward",
      "Janesville",
      "Kenosha",
      "La Crosse",
      "Lake Geneva",
      "Madison",
      "Manitowoc",
      "Marinette",
      "Menasha",
      "Milwaukee",
      "Neenah",
      "New Glarus",
      "Oconto",
      "Oshkosh",
      "Peshtigo",
      "Portage",
      "Prairie du Chien",
      "Racine",
      "Rhinelander",
      "Ripon",
      "Sheboygan",
      "Spring Green",
      "Stevens Point",
      "Sturgeon Bay",
      "Superior",
      "Waukesha",
      "Wausau",
      "Wauwatosa",
      "West Allis",
      "West Bend",
      "Wisconsin Dells"
    ],
    "WY": [
      "Buffalo",
      "Casper",
      "Cheyenne",
      "Cody",
      "Douglas",
      "Evanston",
      "Gillette",
      "Green River",
      "Jackson",
      "Lander",
      "Laramie",
      "Newcastle",
      "Powell",
      "Rawlins",
      "Riverton",
      "Rock Springs",
      "Sheridan",
      "Ten Sleep",
      "Thermopolis",
      "Torrington",
      "Worland"
    ]
  }
];